import assert from 'node:assert/strict';
import {bindHoldControls} from './src/controls.mjs';
import {fresh,move,blocked,props,interact,fight,encode,decode,award,openBox,usePotion} from './src/engine.mjs';
let passed=0;function test(name,fn){fn();passed++;console.log('PASS '+name);}
function approach(s,id){let p=props[s.room].find(p=>p.id===id);s.x=p.x-1;s.y=p.y;}
test('Collision and five connected rooms',()=>{let s=fresh();s.x=1;s.y=1;assert.equal(move(s,-1,0),false);s.y=4;for(let r=0;r<4;r++){s.x=11;assert(move(s,1,0));assert.equal(s.room,r+1);assert.equal(s.x,1);}for(let r=3;r>=0;r--){s.x=1;assert(move(s,-1,0));assert.equal(s.room,r);}approach(s,'fountain');assert.equal(move(s,1,0),false);});
test('A peaceful path through the actual room geometry reaches completion',()=>{let s=fresh();function walk(tx,ty){let q=[[s.x,s.y,[]]],seen=new Set();while(q.length){let [x,y,path]=q.shift();if(x===tx&&y===ty){for(let [dx,dy] of path)assert(move(s,dx,dy));return;}for(let [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){let nx=x+dx,ny=y+dy,k=nx+','+ny;if(!seen.has(k)&&!blocked(s,nx,ny)){seen.add(k);q.push([nx,ny,[...path,[dx,dy]]]);}}}assert.fail('No route');}for(let r=0;r<4;r++){if(r===2){walk(8,3);assert(interact(s,'locker','Open'));}walk(11,4);assert(move(s,1,0));}walk(8,4);assert(interact(s,'stairs','Unlock exit'));assert(s.complete);assert.equal(s.hp,30);assert.equal(s.npcs.rat.state,'neutral');});
test('Healthy player beats worst-case ratman without healing',()=>{let s=fresh();s.room=3;approach(s,'rat');interact(s,'rat','Fight');let calls=0;const rng=()=>calls++%2?0.999:0;while(s.combat)fight(s,'Attack',rng);assert(s.hp>=24);assert.equal(s.npcs.rat.hp,0);assert.equal(s.npcs.rat.state,'dead');});
test('Defend, potions, turn consumption, menu actions, fleeing',()=>{let s=fresh();s.room=3;approach(s,'rat');interact(s,'rat','Fight');let hp=s.hp;assert.equal(interact(s,'rat','Inspect'),false);assert.equal(fight(s,'Use potion'),false);assert.equal(s.hp,hp);fight(s,'Defend',()=>.999);assert.equal(s.hp,29);s.hp=10;fight(s,'Use potion',()=>0);assert.equal(s.hp,18);assert.equal(s.potions,1);fight(s,'Flee',()=>0);assert.equal(s.hp,16);assert.equal(s.combat,null);assert.equal(s.x,1);});
test('Fatal blow stops gameplay and cannot produce a dead save',()=>{let s=fresh();let living=encode(s);s.room=2;approach(s,'mara');interact(s,'mara','Fight');s.hp=1;fight(s,'Defend',()=>0);assert(s.dead);assert.equal(s.combat,null);assert.equal(encode(s),null);assert.equal(move(s,1,0),false);assert.equal(decode(living).hp,30);});
test('Containers, secret and achievement rewards cannot repeat',()=>{let s=fresh();s.room=1;approach(s,'chest');assert(interact(s,'chest','Open'));assert.equal(interact(s,'chest','Open'),false);assert.equal(s.gold,6);approach(s,'crate');interact(s,'crate','Break');assert.equal(s.cheese,1);s.room=3;approach(s,'rat');interact(s,'rat','Offer cheese');assert.equal(s.npcs.rat.state,'friendly');let boxes=s.boxes;award(s,'Cheese diplomacy');assert.equal(s.boxes,boxes);openBox(s);let restored=decode(encode(s));award(restored,'Cheese diplomacy');assert.equal(restored.boxes,0);approach(s,'pipe');interact(s,'pipe','Search');let gold=s.gold;interact(s,'pipe','Search');assert.equal(s.gold,gold);});
test('Mara dialogue, friendship, trade, theft and key recovery',()=>{let s=fresh();s.room=2;approach(s,'mara');interact(s,'mara','Befriend');assert(!s.key);interact(s,'mara','Talk');interact(s,'mara','Befriend');assert(s.key);assert.equal(s.npcs.mara.state,'friendly');s.gold=6;interact(s,'mara','Trade');assert.equal(s.gold,3);interact(s,'mara','Trade');assert.equal(s.gold,3);interact(s,'mara','Steal');assert(s.combat);assert.equal(s.npcs.mara.state,'hostile');while(s.combat&&!s.dead)fight(s,'Attack',()=>.5);assert(!s.dead);assert(s.key);assert.equal(s.npcs.mara.state,'dead');assert.equal(s.hp,15);});
test('Threatening starts combat, full healing works, potions cap at max',()=>{let s=fresh();s.hp=29;usePotion(s);assert.equal(s.hp,30);assert.equal(s.potions,1);assert.equal(usePotion(s),false);s.hp=1;approach(s,'fountain');interact(s,'fountain','Heal');assert.equal(s.hp,30);s.room=2;approach(s,'mara');interact(s,'mara','Threaten');assert(s.key&&s.combat);});
test('Saving restores all persistent fields and rejects malformed data',()=>{let s=fresh();s.gold=7;s.flags.memo=true;s.achievements=['Pipe dream'];let restored=decode(encode(s));assert.deepEqual(restored,s);for(const raw of ['nope','null','{}','{"version":9}',JSON.stringify({...s,hp:0}),JSON.stringify({...s,npcs:null}),JSON.stringify({...s,x:4,y:3}),JSON.stringify({...s,achievements:[1]})])assert.equal(decode(raw),null);s.room=3;approach(s,'rat');interact(s,'rat','Fight');assert.equal(encode(s),null);});
function holdHarness(){let pending=new Map(),id=0,steps=[],allowed=true;class Pad extends EventTarget{disabled=false;dataset={move:'1,0'};classList={add(){},remove(){}};setPointerCapture(){}}const button=new Pad(),other=new Pad();other.dataset.move='0,-1';const controls=bindHoldControls([button,other],{move:(...p)=>steps.push(p),canMove:()=>allowed,setTimer:(fn,delay)=>{pending.set(++id,{fn,delay});return id;},clearTimer:id=>pending.delete(id)});const fire=(type,props={},target=button)=>{const e=new Event(type,{cancelable:true});Object.assign(e,{pointerId:1,...props});target.dispatchEvent(e);};return {button,other,controls,steps,fire,pending,lock:()=>allowed=false,tick:()=>{const [id,{fn,delay}]=pending.entries().next().value;pending.delete(id);fn();return delay;}};}
test('Touch hold repeats and release stops; click does not double-step',()=>{const h=holdHarness();h.fire('pointerdown');assert.equal(h.steps.length,1);assert.equal(h.tick(),270);assert.equal(h.tick(),165);assert.equal(h.steps.length,3);h.fire('pointerup');h.fire('click',{detail:1});assert.equal(h.steps.length,3);assert.equal(h.pending.size,0);h.fire('click',{detail:0});assert.equal(h.steps.length,4);});
test('Cancelled touches and app pause stop held movement',()=>{const h=holdHarness();for(const type of ['pointercancel','lostpointercapture']){h.fire('pointerdown');h.fire(type);assert.equal(h.pending.size,0);}h.fire('pointerdown');h.controls.stop();assert.equal(h.pending.size,0);h.fire('pointerdown');h.lock();h.tick();assert.equal(h.pending.size,0);});
test('Only the active finger owns direction and disabled controls do not move',()=>{const h=holdHarness();h.fire('pointerdown');h.fire('pointerdown',{pointerId:2},h.other);h.fire('pointerup',{pointerId:1});h.tick();assert.deepEqual(h.steps.at(-1),[0,-1]);h.fire('pointerup',{pointerId:2},h.other);assert.equal(h.pending.size,0);h.button.disabled=true;const before=h.steps.length;h.fire('pointerdown');h.fire('click',{detail:0});assert.equal(h.steps.length,before);});
console.log(`\n${passed} gameplay and input checks passed.`);
