import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {bindHoldControls} from './src/controls.mjs';
import {fresh,rooms,props,move,blocked,nearby,placeOf,setPlace,interact,fight,actions,encode,decode,usePotion,useBandage,useWhetstone,openRewardBox,isSafeRoom,attackRange,combatActions,outcome,character,conditionText,applyCondition,clearCondition,hasCondition,coverNear,playerNearHazard,awardXp,chooseStat,xpForNext} from './src/engine.mjs';
import {recordDeed,classOptions,classReady,chooseClass,CLASSES,RACES,activeAbility,abilityReady} from './src/engine.mjs';
import {bandFor,relationshipText,companionOf,blankCompanion,COMPANIONS} from './src/companions.mjs';
import {companionRespect,companionEpilogue,separateCompanions} from './src/engine.mjs';
import {award,achievementFor,ACHIEVEMENTS,BOX_TIERS,BOX_LOOT,ITEMS,gearBonus,itemOf,equipItem,unequipItem,rarityOf,traitOf,abilityBonus,RARITIES,grantedItem,SLOTS,itemSlot,equippedItems,emptyEquipped,FACTIONS,STANDING,factionOf,standingOf,improveStanding,worsenStanding,questState,questCarried,questActionFor,factionLine,keepSupplies,memberStanding,approvalEffect} from './src/engine.mjs';
import {PEOPLE,NPCS,STOCK_KEYS,isWith,withPlayer,priceOf,sellPriceOf} from './src/npcs.mjs';
import {check,modifier,proficiencyBonus,SKILLS,ABILITIES} from './src/rules.mjs';
let passed=0;const pending=[];function test(name,fn){const result=fn();if(result&&typeof result.then==='function')pending.push(result.then(()=>{passed++;console.log('PASS '+name);}));else{passed++;console.log('PASS '+name);}}
function walk(s,tx,ty){const q=[[s.x,s.y,[]]],seen=new Set([s.x+','+s.y]);while(q.length){const [x,y,path]=q.shift();if(x===tx&&y===ty){for(const [dx,dy] of path)assert(move(s,dx,dy));return;}for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,k=nx+','+ny;if(!seen.has(k)&&!blocked(s,nx,ny)){seen.add(k);q.push([nx,ny,[...path,[dx,dy]]]);}}}assert.fail(`No route in ${rooms[s.room]} to ${tx},${ty}`);}
function travel(s,room){while(s.room<room){walk(s,11,4);assert(move(s,1,0));}while(s.room>room){walk(s,1,4);assert(move(s,-1,0));}}
function approach(s,id){for(let attempt=0;attempt<5;attempt++){const room=NPCS[id]?placeOf(s,id).room:props.findIndex(ps=>ps.some(p=>p.id===id));if(s.room!==room)travel(s,room);const p=NPCS[id]?placeOf(s,id):props[room].find(p=>p.id===id);const candidate=[[p.x-1,p.y],[p.x+1,p.y],[p.x,p.y-1],[p.x,p.y+1]].find(([x,y])=>!blocked(s,x,y));walk(s,...candidate);if(nearby(s).some(n=>n.id===id))return;}assert.fail(`Could not reach ${id}`);}
function act(s,id,action,rng=()=>0.5){approach(s,id);assert(actions(s,id).includes(action),`${id} cannot ${action}`);assert(interact(s,id,action,rng));return s;}
function win(s,rng=()=>.5){let safety=0;while(s.combat&&!s.dead){assert(++safety<80);if(s.hp<=8&&s.potions)fight(s,'Use potion',rng);else fight(s,'Attack',rng);}assert(!s.dead,'Player unexpectedly died');}
function checkpoint(s){const raw=encode(s);assert(raw);const restored=decode(raw);assert(restored);assert.deepEqual(restored,s);return restored;}
function supplied(){const s=fresh();s.gold=30;s.potions=6;s.items.repairKits=1;s.flags.memo=true;return s;}
function getKey(s){act(s,'locker','Open');}
function finish(s){act(s,'stairs','Unlock exit');assert(s.complete);return checkpoint(s);}

test('Every prop is reachable and five-room movement still works',()=>{const s=fresh();assert.equal(move(s,3,0),false);for(const ps of props)for(const p of ps)approach(s,p.id);travel(s,0);s.x=1;s.y=1;assert(!move(s,-1,0));});
test('A peaceful player may ignore all NPCs and finish with the spare key',()=>{const s=fresh();getKey(s);finish(s);assert.equal(s.hp,30);for(const id of PEOPLE)assert.equal(s.npcs[id].condition,'conscious');});
test('The original rat encounter remains survivable with no dying retaliation',()=>{const s=fresh();act(s,'rat','Fight');let calls=0;win(s,()=>calls++%2?.999:0);assert(s.hp>=24);assert.equal(s.npcs.rat.condition,'dead');assert.equal(s.gold,2);});
test('Turn control, healing, defending, fleeing, and no turns on invalid actions',()=>{const s=fresh();act(s,'rat','Fight');assert(!fight(s,'Use potion'));assert.equal(s.hp,30);assert(!interact(s,'rat','Inspect'));assert(!move(s,1,0));fight(s,'Defend',()=>.999);assert.equal(s.hp,29);s.hp=10;fight(s,'Use potion',()=>0);assert.equal(s.hp,18);fight(s,'Flee',()=>0);assert.equal(s.hp,16);assert.equal(s.x,1);assert.equal(s.npcs.rat.attitude,'hostile');});
test('Death never overwrites a living checkpoint',()=>{const s=fresh(),raw=encode(s);act(s,'mara','Attack');s.hp=1;fight(s,'Defend',()=>0);assert(s.dead);assert.equal(encode(s),null);assert.equal(decode(raw).hp,30);});
for(const id of PEOPLE){
 test(`${id}: help, friendship, one-time rewards and remembered assistance`,()=>{let s=supplied();act(s,id,'Befriend');assert(!s.npcs[id].memory.befriended);act(s,id,'Talk');act(s,id,'Help');act(s,id,'Befriend');assert.equal(s.npcs[id].attitude,'friendly');assert(s.npcs[id].memory.helped);const boxes=s.boxes,items=JSON.stringify(s.items);act(s,id,'Help');act(s,id,'Befriend');assert.equal(s.boxes,boxes);assert.equal(JSON.stringify(s.items),items);s=checkpoint(s);act(s,id,'Talk');assert(s.npcs[id].memory.befriended);});
 test(`${id}: credible lie, pickpocket, discovery on exit, and no duplicate theft`,()=>{let s=supplied();act(s,id,'Talk');act(s,id,'Lie');assert(s.npcs[id].memory.distracted);const stock=JSON.stringify(s.npcs[id].inventory);act(s,id,'Pickpocket');assert.notEqual(JSON.stringify(s.npcs[id].inventory),stock);assert(s.npcs[id].memory.stolen);const after=JSON.stringify(s.npcs[id].inventory);act(s,id,'Pickpocket');assert.equal(JSON.stringify(s.npcs[id].inventory),after);travel(s,s.room===4?3:s.room+1);assert.equal(s.npcs[id].attitude,'hostile');assert(s.npcs[id].memory.theftDetected);s=checkpoint(s);assert(s.npcs[id].memory.lied);});
 test(`${id}: betrayal cannot be erased by helpful action spam`,()=>{const s=supplied();act(s,id,'Talk');act(s,id,'Help');act(s,id,'Befriend');act(s,id,'Pickpocket');travel(s,s.room===4?3:s.room+1);act(s,id,'Help');act(s,id,'Befriend');assert(s.npcs[id].memory.betrayed);assert.equal(s.npcs[id].attitude,'hostile');});
 test(`${id}: trade stock is finite and payments enter the NPC wallet`,()=>{const s=supplied(),n=s.npcs[id],item=NPCS[id].trade;act(s,id,'Trade');assert(n.memory.traded);assert(s.items[item]>0||s.potions>6);assert(n.inventory.gold>NPCS[id].stock.gold);while(n.inventory[item])act(s,id,'Trade');const before=s.gold;act(s,id,'Trade');assert.equal(s.gold,before);checkpoint(s);});
 test(`${id}: nonlethal defeat, loot, wake, permanent memories and no loot duplication`,()=>{let s=supplied();act(s,id,'Knock unconscious');assert.equal(s.combat.intent,'nonlethal');win(s,()=>.999);assert.equal(s.npcs[id].condition,'unconscious');assert(s.npcs[id].memory.knockedOut);s=checkpoint(s);act(s,id,'Loot');assert(STOCK_KEYS.every(k=>s.npcs[id].inventory[k]===0));const pack=JSON.stringify({items:s.items,gold:s.gold,potions:s.potions});act(s,id,'Loot');assert.equal(JSON.stringify({items:s.items,gold:s.gold,potions:s.potions}),pack);act(s,id,'Wake up');assert.equal(s.npcs[id].condition,'conscious');assert(s.npcs[id].hp>0);assert.equal(s.npcs[id].attitude,'hostile');assert(s.npcs[id].memory.looted);checkpoint(s);});
 test(`${id}: Kill on a conscious NPC starts combat, not instant death`,()=>{const s=supplied();act(s,id,'Kill');assert(s.combat);assert.equal(s.npcs[id].condition,'conscious');assert.equal(s.npcs[id].hp,NPCS[id].hp);win(s);assert.equal(s.npcs[id].condition,'dead');checkpoint(s);assert.deepEqual(actions(s,id),['Inspect','Loot']);});
 test(`${id}: downed execution persists and does not block the exit`,()=>{let s=supplied();act(s,id,'Knock unconscious');win(s,()=>.999);act(s,id,'Kill');assert.equal(s.npcs[id].condition,'dead');assert(s.npcs[id].memory.killed);s=checkpoint(s);getKey(s);finish(s);assert.equal(s.npcs[id].condition,'dead');});
}
test('Threats change attitudes and Vex fights back',()=>{for(const id of PEOPLE){const s=supplied();act(s,id,'Threaten');assert(s.npcs[id].memory.threatened);assert.equal(s.npcs[id].attitude,'hostile');assert.equal(!!s.combat,id==='vex');}});
test('Open robbery: Mara and Tobin surrender; Vex resists',()=>{for(const id of PEOPLE){const s=supplied(),before=s.gold;act(s,id,'Rob openly');assert.equal(s.npcs[id].attitude,'hostile');if(id==='vex'){assert(s.combat);assert(!s.npcs[id].memory.robbed);}else{assert(!s.combat);assert(s.gold>before);assert(s.npcs[id].memory.robbed);assert(STOCK_KEYS.every(k=>s.npcs[id].inventory[k]===0));const gold=s.gold;act(s,id,'Rob openly');assert.equal(s.gold,gold);}}});
// Tests place a second survivor in the room to create a witness. The shipped
// floor holds one character per room, so this arrangement is how the witness
// rule is exercised until two survivors share a room.
function relocate(s,id,room,x,y){const previous={...placeOf(s,id)};setPlace(s,id,room,x,y);return ()=>setPlace(s,id,previous.room,previous.x,previous.y);}
test('A witnessed theft makes the onlooker suspicious and shows up in dialogue',()=>{const s=supplied();const restore=relocate(s,'vex',1,5,5);try{act(s,'tobin','Talk');act(s,'tobin','Lie');act(s,'tobin','Pickpocket');assert(s.npcs.tobin.memory.stolen);assert(s.npcs.vex.memory.sawTheft,'the onlooker should remember the theft');assert.equal(s.npcs.vex.attitude,'suspicious');assert(!s.npcs.vex.memory.stolen,'the onlooker was not the victim');const kept=checkpoint(s);assert(kept.npcs.vex.memory.sawTheft,'witnessed knowledge must survive a save');act(s,'vex','Talk');assert(s.log.at(-1).includes('I saw you take'),'dialogue should refer to what was witnessed');}finally{restore();}});
test('An unwitnessed theft is known only to the victim',()=>{const s=supplied();act(s,'tobin','Talk');act(s,'tobin','Lie');act(s,'tobin','Pickpocket');assert(s.npcs.tobin.memory.stolen);assert(!s.npcs.vex.memory.sawTheft,'nobody was there to see it');assert(!s.npcs.vex.memory.sawRob);assert.equal(s.npcs.vex.attitude,'neutral');act(s,'vex','Talk');assert(!s.log.at(-1).includes('I saw you take'));travel(s,2);assert(s.npcs.tobin.memory.theftDetected,'the victim still notices on exit');assert(!s.npcs.vex.memory.sawTheft);});
test('A witnessed attack turns the onlooker suspicious, and a killing turns them hostile',()=>{const s=supplied();const restore=relocate(s,'vex',1,5,5);try{act(s,'tobin','Attack');assert(s.npcs.vex.memory.sawAttack);assert.equal(s.npcs.vex.attitude,'suspicious');win(s);assert(s.npcs.vex.memory.sawKill,'the killing blow should be witnessed');assert.equal(s.npcs.vex.attitude,'hostile');}finally{restore();}});
test('A witnessed helpful action warms the onlooker',()=>{const s=supplied();const restore=relocate(s,'mara',1,5,5);try{act(s,'tobin','Help');assert(s.npcs.tobin.memory.helped);assert(s.npcs.mara.memory.sawHelp,'the onlooker should remember the help');assert.equal(s.npcs.mara.attitude,'friendly');act(s,'mara','Talk');assert(s.log.at(-1).includes('I saw you help'),'dialogue should refer to what was witnessed');}finally{restore();}});
test('Vex reacts to a robbery he saw and refuses friendship',()=>{let s=supplied();const restore=relocate(s,'vex',1,5,5);try{act(s,'tobin','Rob openly');s=checkpoint(s);assert(s.npcs.vex.memory.sawRob);assert.equal(s.npcs.vex.attitude,'hostile');act(s,'vex','Talk');assert(s.log.at(-1).includes('I watched you take'));act(s,'vex','Help');act(s,'vex','Befriend');assert(!s.npcs.vex.memory.befriended);}finally{restore();}});
test('Exposed lies, failed thefts and missing help supplies have real outcomes',()=>{for(const id of PEOPLE){let s=fresh();s.potions=0;s.gold=0;s.items.bandages=0;act(s,id,'Help');assert(!s.npcs[id].memory.helped);act(s,id,'Lie');assert(s.npcs[id].memory.lieExposed);act(s,id,'Pickpocket',()=>0);assert(s.npcs[id].memory.theftAttempt);assert.equal(s.npcs[id].attitude,'hostile');s=supplied();act(s,id,'Talk');act(s,id,'Lie');act(s,id,'Talk');assert(s.npcs[id].memory.lieExposed);assert.equal(s.npcs[id].attitude,'hostile');}});
test('Pickpocket resolves as a Sleight of Hand check against the target',()=>{const s=supplied();act(s,'tobin','Talk');act(s,'tobin','Lie');const stock=JSON.stringify(s.npcs.tobin.inventory);act(s,'tobin','Pickpocket');assert.notEqual(JSON.stringify(s.npcs.tobin.inventory),stock,'a distracted target is robbed successfully');assert(s.log.at(-1).includes('Sleight of hand'),'the check should be reported');assert(s.log.at(-1).includes('with advantage'));assert(s.log.at(-1).includes('Success'));const alert=supplied();act(alert,'tobin','Talk');act(alert,'tobin','Pickpocket');assert(alert.log.at(-1).includes('with disadvantage'),'an alert target is harder to rob');assert(alert.log.at(-1).includes('against DC 11'),'the DC comes from the target Wisdom and Perception');const failed=supplied();act(failed,'tobin','Talk');act(failed,'tobin','Lie');const kept=JSON.stringify(failed.npcs.tobin.inventory);act(failed,'tobin','Pickpocket',()=>0);assert.equal(JSON.stringify(failed.npcs.tobin.inventory),kept,'a failed check steals nothing');assert(failed.log.at(-1).includes('Failure'));assert.equal(failed.npcs.tobin.attitude,'hostile');});
test('Steal a loose owned item unseen',()=>{const s=supplied();act(s,'vex','Knock unconscious');win(s);assert.equal(s.npcs.vex.condition,'unconscious');act(s,'whetstone','Take');assert.equal(s.items.whetstones,1,'the whetstone is taken');assert.equal(s.stolen.whetstones,'vex','the item remembers its owner');assert(!s.npcs.vex.memory.stolen,'an unconscious owner notices nothing');assert(!s.npcs.vex.memory.theftDetected);assert(s.log.some(line=>line.includes('Nobody is watching')));assert.equal(checkpoint(s).stolen.whetstones,'vex','provenance survives a save');});
test('Steal an owned item while watched',()=>{const s=supplied();const restore=relocate(s,'mara',1,5,4);try{const before=s.gold;act(s,'satchel','Open');assert.equal(s.gold,before+3);assert.equal(s.items.smokeBombs,1);assert.equal(s.stolen.smokeBombs,'tobin');assert(s.npcs.tobin.memory.theftDetected,'the owner records the theft');assert(s.npcs.tobin.memory.demanded);assert.equal(s.npcs.tobin.attitude,'hostile');assert(s.npcs.mara.memory.sawTheft,'the bystander records what they saw');assert.equal(s.npcs.mara.attitude,'suspicious');assert.equal(checkpoint(s).stolen.smokeBombs,'tobin');}finally{restore();}});
test('Loot an owned container unseen',()=>{const s=supplied();act(s,'tobin','Knock unconscious');win(s);const before=s.gold;act(s,'satchel','Open');assert.equal(s.gold,before+3,'the container is emptied');assert.equal(s.stolen.gold,'tobin');assert(!s.npcs.tobin.memory.theftDetected,'an unconscious owner notices nothing');assert(s.log.some(line=>line.includes('Nobody is watching')));});
test('Get confronted after being caught and hand the item back',()=>{const s=supplied();act(s,'satchel','Open');assert(s.npcs.tobin.memory.demanded,'the owner demands it back');assert(s.log.some(line=>line.includes('I counted those twice')));assert(actions(s,'tobin').includes('Hand it back'),'the return action is offered');const before=s.gold;act(s,'tobin','Hand it back');assert(!s.stolen.gold&&!s.stolen.smokeBombs,'the claim is settled');assert.equal(s.gold,before-3,'the coins go back');assert.equal(s.npcs.tobin.inventory.gold,9,'the owner is repaid');assert(s.npcs.tobin.memory.returned);assert.equal(s.npcs.tobin.attitude,'suspicious');const attacked=supplied();approach(attacked,'whetstone');setPlace(attacked,'vex',4,7,5);interact(attacked,'whetstone','Take');assert(attacked.combat&&attacked.combat.enemy==='vex','Vex attacks rather than asking');});
test('Owned-item provenance is validated and survives a save',()=>{const s=fresh();assert.equal(decode(JSON.stringify({...s,stolen:{gold:'nobody'}})),null,'an unknown owner is rejected');assert.equal(decode(JSON.stringify({...s,stolen:{gold:7}})),null,'a non-name owner is rejected');s.stolen.whetstones='vex';assert.equal(checkpoint(s).stolen.whetstones,'vex');});
function recruitMara(s){act(s,'mara','Talk');act(s,'mara','Help');act(s,'mara','Befriend');act(s,'mara','Recruit');assert(isWith(s,'mara'),'Mara should have joined');return s;}
test('Recruit an NPC who trusts you',()=>{const s=supplied();act(s,'mara','Talk');act(s,'mara','Help');act(s,'mara','Befriend');assert(!isWith(s,'mara'),'befriending is not recruiting');act(s,'mara','Recruit');assert(s.party.includes('mara'),'Mara joins the party');assert(s.npcs.mara.memory.recruited);assert(s.log.some(line=>line.includes('joins you')),'the recruiter announces it');assert(s.log.some(line=>line.includes('Persuasion')));assert(nearby(s).some(p=>p.id==='mara'),'a follower stands beside the player');});
test('Recruitment can be refused',()=>{const early=supplied();act(early,'tobin','Talk');act(early,'tobin','Recruit');assert(!isWith(early,'tobin'),'an unfinished request is not enough');assert(early.log.at(-1).includes('refuses until'));const caught=supplied();act(caught,'tobin','Rob openly');act(caught,'tobin','Recruit');assert(!isWith(caught,'tobin'),'someone you robbed will not travel with you');assert(caught.log.at(-1).includes('refuses'));});
test('Fight alongside a recruited NPC',()=>{const s=recruitMara(supplied());act(s,'rat','Fight');assert(s.combat);fight(s,'Attack',()=>0.5);assert.equal(s.combat.pendingCompanion,'mara','Mara waits for a call');assert(s.log.some(line=>line.includes('waiting on your call')));fight(s,'Mara: Strike',()=>0.5);assert(s.log.some(line=>line.includes('Mara hits Ratman scrapper')),'the companion strikes when told');assert.equal(s.hp,s.maxHp,'the follower takes the hit instead');assert(s.npcs.mara.hp<20,'the follower uses their own hit points');assert.equal(s.npcs.rat.hp,1,'both blows landed');});test('Form a temporary alliance',()=>{const s=supplied();act(s,'tobin','Talk');act(s,'tobin','Help');act(s,'tobin','Recruit');assert.equal(s.allies.tobin,2,'Tobin agrees to two fights');assert(!s.party.includes('tobin'),'he does not join permanently');assert(withPlayer(s).includes('tobin'));const kept=checkpoint(s);assert.equal(kept.allies.tobin,2);act(s,'rat','Fight');win(s);assert.equal(s.allies.tobin,1,'one fight is spent');assert(withPlayer(s).includes('tobin'));assert(s.log.some(line=>line.includes('Tobin hits')));});
test('Betraying an ally ends the alliance',()=>{const s=recruitMara(supplied());act(s,'mara','Attack');assert(!s.party.includes('mara'),'she leaves the party');assert(!isWith(s,'mara'));assert.equal(s.npcs.mara.attitude,'hostile');assert(s.npcs.mara.memory.abandoned);assert(s.combat&&s.combat.enemy==='mara','and fights back');assert(s.log.some(line=>line.includes('no longer with you')));});
test('A recruited NPC survives a save and reload',()=>{const s=recruitMara(supplied());s.npcs.mara.hp=13;const kept=checkpoint(s);assert(kept.party.includes('mara'));assert(isWith(kept,'mara'));assert.equal(kept.npcs.mara.hp,13,'their health is saved');assert.equal(kept.npcs.mara.inventory.gold,s.npcs.mara.inventory.gold,'their inventory is saved');assert(nearby(kept).some(p=>p.id==='mara'),'they are still beside the player');assert.equal(decode(JSON.stringify({...kept,party:['nobody']})),null,'an unknown recruit is rejected');assert.equal(decode(JSON.stringify({...kept,allies:{mara:1.5}})),null,'a malformed alliance is rejected');});
test('Buy an item from an NPC',()=>{const s=supplied(),n=s.npcs.mara;const price=priceOf(s,'mara','potions');assert.equal(price,3,'a neutral seller charges their own price');act(s,'mara','Ask about goods');assert(s.log.at(-1).includes('Mara sells'),'goods can be inspected');assert(s.log.at(-1).includes('potion for 3 coins'));act(s,'mara','Trade');assert.equal(n.inventory.potions,1,'the stock leaves the seller');assert.equal(s.potions,7,'the player receives it');assert.equal(s.gold,30-price,'the player pays the asking price');assert.equal(n.inventory.gold,3+price,'the seller is paid');});
test('Sell an item to an NPC',()=>{const s=supplied(),n=s.npcs.tobin;const price=sellPriceOf(s,'tobin','bandages');assert.equal(s.items.bandages,1);act(s,'tobin','Sell 1 bandage');assert.equal(s.items.bandages,0,'the item leaves the player');assert.equal(n.inventory.bandages,1,'and joins the seller stock');assert.equal(s.gold,30+price,'the player is paid');assert.equal(n.inventory.gold,6-price,'the buyer pays from their own purse');});
test('A friendly NPC offers better deals',()=>{const s=supplied();const neutral=priceOf(s,'mara','potions');act(s,'mara','Talk');act(s,'mara','Help');act(s,'mara','Befriend');const friendly=priceOf(s,'mara','potions');assert(friendly<neutral,'friends pay less than strangers');assert.equal(friendly,2);assert(sellPriceOf(s,'mara','potions')>Math.floor(neutral/2),'and earn more when selling');act(s,'mara','Ask about goods');assert(s.log.at(-1).includes('potion for 2 coins'));});
test('A hostile NPC refuses to trade',()=>{const s=supplied();act(s,'mara','Rob openly');assert.equal(s.npcs.mara.attitude,'hostile');const before=JSON.stringify(s.npcs.mara.inventory);assert(!actions(s,'mara').includes('Trade'),'no trade actions are offered');assert(!actions(s,'mara').includes('Ask about goods'));approach(s,'mara');assert.equal(interact(s,'mara','Trade'),false,'the trade action is rejected');assert.equal(JSON.stringify(s.npcs.mara.inventory),before,'and nothing changes hands');});
test('Trading survives a save and reload',()=>{const s=supplied();act(s,'mara','Trade');act(s,'tobin','Sell 1 bandage');const kept=checkpoint(s);assert.equal(kept.npcs.mara.inventory.potions,1);assert.equal(kept.npcs.mara.inventory.gold,6,'the seller keeps the coins they were paid');assert.equal(kept.npcs.tobin.inventory.bandages,1);assert.equal(kept.potions,7);assert.equal(kept.gold,29,'both transactions are reflected in the purse');});
test('Loot after a trade keeps their stock consistent',()=>{const s=supplied();s.npcs.tobin.inventory.repairKits=1;const before=s.items.smokeBombs;act(s,'tobin','Trade');const bought=s.items.smokeBombs;assert.equal(bought,before+1,'one smoke bomb is bought');assert.equal(s.npcs.tobin.inventory.smokeBombs,1,'leaving one in their stock');act(s,'tobin','Knock unconscious');win(s);act(s,'tobin','Loot');assert.equal(s.items.smokeBombs,bought+1,'only the remaining bomb can be looted');assert.equal(s.npcs.tobin.inventory.smokeBombs,0,'the sold bomb does not reappear');assert.equal(s.npcs.tobin.inventory.repairKits,1,'equipped gear stays with them');assert.equal(s.npcs.tobin.inventory.potions,0,'everything else is taken');});
test('An NPC moves between rooms on its routine',()=>{const s=fresh();assert.equal(placeOf(s,'tobin').room,1,'Tobin starts among the loot in Lost Property');travel(s,1);assert.equal(placeOf(s,'tobin').room,1,'nobody wanders while the player is in the room');travel(s,0);assert.equal(placeOf(s,'tobin').room,3,'the scavenger moves on to the Pest Control pipe');travel(s,1);travel(s,0);assert.equal(placeOf(s,'tobin').room,1,'and works back again');});
test('An NPC reacts to violence nearby',()=>{const s=supplied();approach(s,'tobin');setPlace(s,'vex',3,4,4);interact(s,'tobin','Attack');assert(s.npcs.mara.memory.heardViolence,'the neighbour heard the fight');assert.equal(placeOf(s,'mara').room,3,'and withdrew away from the noise');assert.equal(placeOf(s,'vex').room,2,'the patroller closed in on the trouble without joining');assert(s.npcs.vex.memory.heardViolence);assert.equal(placeOf(s,'tobin').room,1,'while the combatant stays put');});
test('An NPC flees from danger in their room',()=>{const s=supplied();approach(s,'rat');setPlace(s,'tobin',3,5,6);assert.equal(placeOf(s,'tobin').room,3);interact(s,'rat','Fight');assert(s.combat&&s.combat.enemy==='rat');assert.equal(placeOf(s,'tobin').room,2,'the scavenger gets out of the room');assert(s.npcs.tobin.memory.fled,'and remembers running');assert.notEqual(placeOf(s,'mara').room,3,'the nervous survivor keeps away too');});
test('A recruit follows the player between rooms',()=>{const s=recruitMara(supplied());assert.equal(placeOf(s,'mara').room,s.room);travel(s,0);assert.equal(placeOf(s,'mara').room,0,'she comes along');assert(nearby(s).some(p=>p.id==='mara'),'and stands beside the player');travel(s,3);assert.equal(placeOf(s,'mara').room,3);assert(s.npcs.mara.memory.fled===undefined,'a follower does not run off on her own');});
test('NPC locations survive a save and reload',()=>{const s=supplied();setPlace(s,'vex',2,4,4);setPlace(s,'tobin',3,5,6);const kept=checkpoint(s);assert.equal(placeOf(kept,'vex').room,2);assert.equal(placeOf(kept,'tobin').room,3);assert.deepEqual(kept.places.tobin,s.places.tobin);const patched=decode(JSON.stringify({...s,places:{tobin:{room:9,x:1,y:1}}}));assert(patched,'a bad location must not destroy the save');assert.equal(patched.places.tobin.room,1,'it falls back to the home room');assert.equal(patched.places.vex.room,4,'missing locations fall back to home');});
const dice=(...values)=>{let index=0;return()=>values[Math.min(index++,values.length-1)];};
test('Knock an enemy prone',()=>{const s=supplied();act(s,'rat','Fight');assert(!hasCondition(s,'rat','prone'));fight(s,'Shove',()=>0.9);assert(hasCondition(s,'rat','prone'),'a shove puts them on the floor');assert(conditionText(s,'rat').includes('prone'),'and the condition is shown');const downed=supplied();act(downed,'rat','Fight');applyCondition(downed,'player','prone',2,()=>{});fight(downed,'Attack',dice(0.9,0.1,0.9));assert.equal(downed.hp,27,'a prone defender is easier to hit');const upright=supplied();act(upright,'rat','Fight');fight(upright,'Attack',dice(0.9,0.1,0.9));assert.equal(upright.hp,28,'the same rolls favour a defender on their feet');});
test('Apply Burning from the brazier',()=>{const s=supplied();act(s,'rat','Fight');assert(combatActions(s).includes('Tip the brazier'),'the room hazard is available');fight(s,'Tip the brazier',()=>0.5);assert(hasCondition(s,'rat','burning'));const before=s.npcs.rat.hp;fight(s,'Defend',()=>0.5);assert.equal(s.npcs.rat.hp,before-2,'burning deals 2 at the end of the round');assert(!combatActions(s).includes('Tip the brazier'),'the brazier is used up');});
test('Apply Bleeding with a telling blow',()=>{const s=supplied();act(s,'rat','Fight');fight(s,'Attack',()=>0.999);assert(hasCondition(s,'rat','bleeding'),'a full-damage hit opens a wound');const before=s.npcs.rat.hp;fight(s,'Defend',()=>0.5);assert.equal(s.npcs.rat.hp,before-1,'bleeding costs a point each round');});
test('Grapple an enemy',()=>{const s=supplied();act(s,'rat','Fight');fight(s,'Grapple',dice(0.9,0.05));assert(hasCondition(s,'rat','grappled'),'the hold survives the escape attempt');assert(conditionText(s,'rat').includes('grappled'));const before=s.npcs.rat.hp;fight(s,'Attack',()=>0.5);assert(s.npcs.rat.hp<before,'the player can still strike a grappled enemy');});
test('Conditions expire and can be removed',()=>{const s=supplied();act(s,'rat','Fight');fight(s,'Shove',()=>0.9);assert(hasCondition(s,'rat','prone'));fight(s,'Shove',()=>0.9);assert(hasCondition(s,'rat','stunned'),'shoving someone already down stuns them');fight(s,'Defend',()=>0.5);fight(s,'Defend',()=>0.5);assert(!hasCondition(s,'rat','stunned'),'a stun expires after a couple of rounds');assert(!hasCondition(s,'rat','prone'),'and the prone wears off');const burn=supplied();act(burn,'rat','Fight');fight(burn,'Tip the brazier',()=>0.5);for(let round=0;round<3;round++)fight(burn,'Defend',()=>0.5);assert(!hasCondition(burn,'rat','burning'),'burning burns itself out');const bleed=supplied();act(bleed,'rat','Fight');applyCondition(bleed,'player','bleeding',3,()=>{});assert(combatActions(bleed).includes('Treat bleeding'));fight(bleed,'Treat bleeding',()=>0.5);assert(!hasCondition(bleed,'player','bleeding'),'a bandage stops the bleeding');assert.equal(bleed.items.bandages,0,'and is consumed');});
test('Conditions change how combat resolves',()=>{const stunned=supplied();act(stunned,'rat','Fight');applyCondition(stunned,'rat','stunned',2,()=>{});const hp=stunned.hp;fight(stunned,'Defend',()=>0.999);assert.equal(stunned.hp,hp,'a stunned enemy cannot answer');const poisoned=supplied();act(poisoned,'rat','Fight');applyCondition(poisoned,'player','poisoned',3,()=>{});fight(poisoned,'Attack',dice(0.5,0.1));assert.equal(poisoned.npcs.rat.hp,7,'poison makes the player hit for less');const clean=supplied();act(clean,'rat','Fight');fight(clean,'Attack',dice(0.5,0.1));assert.equal(clean.npcs.rat.hp,6,'an unpoisoned crawler hits harder');const stuck=supplied();act(stuck,'rat','Fight');applyCondition(stuck,'player','grappled',3,()=>{});assert(!combatActions(stuck).includes('Flee'),'a grapple pins the player in place');assert(combatActions(stuck).includes('Break free'));fight(stuck,'Break free',()=>0.9);assert(!hasCondition(stuck,'player','grappled'),'athletics breaks the hold');});
const brawl=(id,room,x,y,px,py)=>{const s=supplied();setPlace(s,id,room,x,y);s.room=room;s.x=px;s.y=py;interact(s,id,'Fight');return s;};
test('Ratman scrapper rushes and shoves near hazards',()=>{const s=brawl('rat',3,9,5,10,5);fight(s,'Defend',()=>0.9);assert(hasCondition(s,'player','prone'),'the scrapper shoves a target standing by the fire');assert(s.log.some(line=>line.includes('shoves you off your feet')));const away=brawl('rat',3,6,4,6,5);fight(away,'Back off',()=>0.9);assert.equal(away.combat.range,1,'the scrapper closes the distance again');assert(away.log.some(line=>line.includes('rushes in')));fight(away,'Defend',()=>0.9);assert(!hasCondition(away,'player','prone'),'away from the hazard it just swings');assert(away.log.some(line=>line.includes('hits for')),'and takes its melee attack');});
test('Ratman skulker keeps distance, uses cover and breaks off',()=>{const s=brawl('skulker',1,8,5,7,5);assert(coverNear(s,'skulker'),'the crate is cover');fight(s,'Defend',()=>0.5);assert(s.combat.cover.skulker,'it ducks behind cover');assert(s.log.some(line=>line.includes('ducks behind cover')));fight(s,'Attack',dice(0.9,0.1));assert.equal(s.npcs.skulker.hp,5,'cover makes the shot harder: the lower die is kept');fight(s,'Defend',()=>0.5);assert(s.combat.range>1||s.log.some(line=>line.includes('gives ground')),'it backs away');fight(s,'Defend',()=>0.5);assert(s.log.some(line=>line.includes('throws something')),'and throws from range');s.npcs.skulker.hp=3;fight(s,'Defend',()=>0.5);assert(!s.combat,'a badly hurt skulker breaks off');assert(s.npcs.skulker.memory.fled);});
test('Ratman brute is slow, tough and wrestles',()=>{const s=brawl('brute',2,2,6,2,5);assert.equal(NPCS.brute.hp,24);fight(s,'Defend',()=>0.9);assert(hasCondition(s,'player','grappled'),'the brute grabs the player');assert(s.log.some(line=>line.includes('seizes hold')));fight(s,'Break free',()=>0.05);assert(hasCondition(s,'player','grappled'),'and the hold is hard to break');const far=brawl('brute',2,2,6,2,5);fight(far,'Back off',()=>0.5);assert.equal(far.combat.range,1,'the brute spends its turn closing again');assert(far.log.some(line=>line.includes('closes the distance')),'slow, but it keeps coming');});
test('Two archetypes fight together and act differently',()=>{const s=supplied();setPlace(s,'rat',3,9,5);setPlace(s,'brute',3,8,5);s.room=3;s.x=10;s.y=5;interact(s,'rat','Fight');assert.equal(s.combat.enemies.length,2,'the pack joins in');assert(s.log.some(line=>line.includes('Ratman brute joins the fight')));assert(combatActions(s).includes('Switch target'),'a target can be chosen');fight(s,'Defend',()=>0.9);assert(s.log.some(line=>line.includes('shoves you off your feet')),'the scrapper uses the hazard');assert(s.log.some(line=>line.includes('Ratman brute')&&line.includes('hits for')||line.includes('Ratman brute seizes')||line.includes('Ratman brute tries')),'the brute answers differently');assert(hasCondition(s,'player','prone'),'and the shove landed');});
test('Gain XP from defeating an enemy',()=>{const s=supplied();approach(s,'rat');const before=s.xp;interact(s,'rat','Fight');win(s);assert(s.xp>=before+NPCS.rat.xp,'the scrapper is worth its XP');assert(s.achievements.includes('First Blood'),'and the first kill is logged');assert(s.log.some(line=>line.includes('XP: defeating Ratman scrapper')));});
test('Gain XP from a noncombat solution',()=>{const s=supplied();approach(s,'rat');const before=s.xp;interact(s,'rat','Sneak past');assert(s.xp>=before+30,'sneaking past earns XP without a fight');assert(s.log.some(line=>line.includes('XP: resolving the custodian without a fight')));assert(!s.npcs.rat.memory.attacked,'and nobody was hurt');assert.equal(s.npcs.rat.attitude,'neutral','or upset');const cheese=supplied();act(cheese,'crate','Break');const beforeCheese=cheese.xp;act(cheese,'rat','Offer cheese');assert(cheese.xp>beforeCheese,'paying the toll also counts');});
test('Level up and spend the stat increase',()=>{const s=fresh();assert.equal(s.level,1);assert.equal(s.maxHp,30);awardXp(s,xpForNext(1),'testing');assert.equal(s.level,2);assert.equal(s.maxHp,35,'levelling raises maximum HP');assert.equal(s.pending,1,'and grants one choice');assert.equal(s.hp,35,'and tops the crawler up');const before=s.abilities.strength,bonus=character(s);awardXp(s,100,'testing again');assert.equal(s.level,3);assert.equal(s.pending,2,'each level grants its own choice');assert(chooseStat(s,'strength'));assert.equal(s.abilities.strength,before+1);assert.equal(s.pending,1);assert(!chooseStat(s,'luck'),'unknown abilities are refused');});
test('Stat increases change the checks immediately',()=>{const s=fresh();const before=check({actor:character(s),skill:'athletics',dc:10,rng:()=>0.5});awardXp(s,100,'testing');awardXp(s,100,'more testing');chooseStat(s,'strength');chooseStat(s,'strength');const after=check({actor:character(s),skill:'athletics',dc:10,rng:()=>0.5});assert.equal(after.abilityModifier,before.abilityModifier+1,'more Strength moves the modifier');assert.equal(after.total,before.total+1);const grapple=supplied();grapple.level=5;grapple.abilities.strength=20;const strong=check({actor:character(grapple),skill:'athletics',dc:10,rng:()=>0.5});assert.equal(strong.abilityModifier,5);assert.equal(strong.proficiencyBonus,3,'level 5 raises the proficiency bonus');});
test('XP, level and stats survive a save and reload',()=>{const s=fresh();awardXp(s,xpForNext(1),'testing');chooseStat(s,'wisdom');s.xp=137;const kept=checkpoint(s);assert.equal(kept.xp,137);assert.equal(kept.level,2);assert.equal(kept.maxHp,35);assert.equal(kept.pending,0);assert.equal(kept.abilities.wisdom,s.abilities.wisdom);assert.equal(check({actor:character(kept),skill:'perception',dc:10,rng:()=>0.5}).abilityModifier,modifierFor(kept.abilities.wisdom),'reloaded stats drive the checks');assert.equal(decode(JSON.stringify({...s,xp:-5})),null,'negative XP is rejected');assert.equal(decode(JSON.stringify({...s,maxHp:12})),null,'an impossible maximum HP is rejected');});
function modifierFor(score){return Math.floor((score-10)/2);}
const seeded=(a)=>()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return ((t^t>>>14)>>>0)/4294967296;};
const approvalOf=s=>companionOf(s,'mara').approval;
const makeFriends=()=>{const s=recruitMara(supplied());act(s,'tobin','Talk');act(s,'tobin','Help');act(s,'vex','Talk');act(s,'vex','Help');return s;};
test('A companion changes how other survivors judge you',()=>{const loyal=makeFriends();companionOf(loyal,'mara').approval=70;assert.equal(companionRespect(loyal),2,'a loyal companion vouches for you');const hostile=makeFriends();companionOf(hostile,'mara').left=true;assert.equal(companionRespect(hostile),-2,'and one who walked out counts against you');const neutral=fresh();assert.equal(companionRespect(neutral),0);});
test('Fleeing leaves an unconscious companion behind',()=>{const s=makeFriends();approach(s,'rat');interact(s,'rat','Fight');s.npcs.mara.condition='unconscious';s.npcs.mara.hp=0;fight(s,'Flee',()=>0.5);const mate=companionOf(s,'mara');assert(mate.separated,'she is separated rather than still recruited');assert(!mate.recruited&&!s.party.includes('mara'));assert.equal(placeOf(s,'mara').room,2,'she is left where she lives');assert(s.log.some(line=>line.includes('She is still back there')));s.npcs.mara.condition='conscious';s.npcs.mara.hp=12;approach(s,'mara');assert(actions(s,'mara').includes('Ask her to rejoin'));interact(s,'mara','Ask her to rejoin');assert(companionOf(s,'mara').recruited&&!companionOf(s,'mara').separated);assert(s.party.includes('mara'));const hostile=makeFriends();const cold=companionOf(hostile,'mara');cold.separated=true;cold.recruited=false;hostile.party=hostile.party.filter(id=>id!=='mara');cold.approval=-70;approach(hostile,'mara');interact(hostile,'mara','Ask her to rejoin');assert(!companionOf(hostile,'mara').recruited,'a hostile companion refuses to come back');assert(hostile.log.some(line=>line.includes('Find someone else')));});
test('An unfinished companion quest gets an epilogue',()=>{const unfinished=makeFriends();approach(unfinished,'mara');interact(unfinished,'mara','Attack');let guard=0;while(unfinished.combat&&guard++<20)fight(unfinished,'Attack',()=>0.999);assert.equal(unfinished.npcs.mara.condition,'dead');assert(companionEpilogue(unfinished).some(line=>line.includes('before anyone found out what happened to Dell')));assert(outcome(unfinished).includes('Dell'));const resolved=makeFriends();act(resolved,'rat','Sneak past');act(resolved,'crate','Break');resolved.cheese=1;act(resolved,'rat','Offer cheese');travel(resolved,0);act(resolved,'mara','Check in with her');act(resolved,'mara','Check in with her');act(resolved,'mara','Check in with her');act(resolved,'pipe','Search');act(resolved,'mara','Give her the locket');resolved.npcs.mara.condition='dead';assert(companionEpilogue(resolved).some(line=>line.includes('got her locket back and then died')));const walked=makeFriends();companionOf(walked,'mara').left=true;assert(companionEpilogue(walked).some(line=>line.includes('walked away and did not come back')));const behind=makeFriends();companionOf(behind,'mara').separated=true;companionOf(behind,'mara').recruited=false;assert(companionEpilogue(behind).some(line=>line.includes('was left behind in the building')));assert(companionEpilogue(fresh()).length===0);});test('Test A: a positive relationship builds trust',()=>{const s=makeFriends();act(s,'rat','Sneak past');act(s,'crate','Break');s.cheese=1;act(s,'rat','Offer cheese');assert(approvalOf(s)>0,'helping allies and avoiding fights earns approval');assert(bandFor(approvalOf(s)).key==='friendly','that is enough for her to open up');assert.equal(companionOf(s,'mara').recruited,true);travel(s,0);act(s,'mara','Check in with her');act(s,'mara','Check in with her');act(s,'mara','Check in with her');assert.equal(companionOf(s,'mara').quest.stage,'searching','talking in a safe room starts her errand');act(s,'pipe','Search');assert.equal(companionOf(s,'mara').quest.stage,'found');assert(s.gear.includes('Sable locket'),'the locket turns up in the pipe');act(s,'mara','Give her the locket');assert.equal(companionOf(s,'mara').quest.outcome,'returned');assert(companionOf(s,'mara').memories.questHelped&&companionOf(s,'mara').memories.sharedLoot);assert(approvalOf(s)>=25,'delivering the locket earns her trust');assert(['friendly','loyal'].includes(bandFor(approvalOf(s)).key));assert(relationshipText(companionOf(s,'mara')).length>0);assert(!relationshipText(companionOf(s,'mara')).includes(String(approvalOf(s))),'the number stays hidden');});
test('Test B: mistreating people cools her off',()=>{const s=recruitMara(supplied());const before=approvalOf(s);act(s,'tobin','Rob openly');assert(approvalOf(s)<before,'robbing a survivor costs approval');assert.equal(bandFor(approvalOf(s)).key,'neutral','one robbery is not the end of it');act(s,'tobin','Talk');approvalEffect(s,'mara',-25,'you killed someone harmless');assert(bandFor(approvalOf(s)).key!=='friendly');const cold=approvalOf(s);approvalEffect(s,'mara',-70,'you pushed her too far');assert.equal(bandFor(approvalOf(s)).key,'hostile');assert(companionOf(s,'mara').memories.betrayed||companionOf(s,'mara').memories.impressed);assert(cold!==approvalOf(s));});
test('Test C: betrayal ends the relationship',()=>{const s=makeFriends();assert(approvalOf(s)>0,'trust first');approach(s,'mara');interact(s,'mara','Attack');assert(companionOf(s,'mara').left,'attacking her ends the partnership');assert(companionOf(s,'mara').hostile);assert(companionOf(s,'mara').memories.attacked);assert(approvalOf(s)<=-60);assert(!s.party.includes('mara'));assert(s.log.some(line=>line.includes('leaves the party')));assert(relationshipText(companionOf(s,'mara')).includes('Gone'));});
test('Test D: her turn, her gear and her stats',()=>{const s=makeFriends();grantedItem(s,'Ratfang Shiv');act(s,'mara','Give her Ratfang Shiv');assert.equal(companionOf(s,'mara').equipped.weapon,'Ratfang Shiv','she equips what she is handed');assert.equal(companionOf(s,'mara').gear.length,0);approach(s,'rat');interact(s,'rat','Fight');fight(s,'Attack',()=>0.5);assert.equal(s.combat.pendingCompanion,'mara','her turn is called');fight(s,'Mara: Strike',()=>0.5);assert(s.log.some(line=>line.includes('Mara hits Ratman scrapper for 6')),'her equipped weapon adds damage');assert(s.npcs.mara.hp<=20,'she has her own health');const kept=checkpoint(s);assert.equal(companionOf(kept,'mara').equipped.weapon,'Ratfang Shiv','equipment persists');});
test('Test E: killing her does not stop the game',()=>{const s=makeFriends();approach(s,'mara');interact(s,'mara','Attack');let guard=0;while(s.combat&&guard++<20)fight(s,'Attack',()=>0.999);assert.equal(s.npcs.mara.condition,'dead');assert(!s.party.includes('mara'));act(s,'mara','Loot');assert(s.log.some(line=>line.includes('You take'))||s.log.some(line=>line.includes('nothing left')));const main=supplied();getKey(main);finish(main);assert(main.complete,'the main dungeon is still completable');const kept=checkpoint(s);assert.equal(kept.npcs.mara.condition,'dead','she stays dead across a save');});
test('Test F: every companion field survives a save',()=>{const s=makeFriends();grantedItem(s,'Last Laugh Boots');act(s,'mara','Give her Last Laugh Boots');travel(s,0);act(s,'mara','Check in with her');act(s,'mara','Check in with her');act(s,'mara','Check in with her');act(s,'pipe','Search');s.npcs.mara.hp=9;applyCondition(s,'mara','bleeding',2,()=>{});const kept=checkpoint(s);const a=companionOf(s,'mara'),b=companionOf(kept,'mara');assert.equal(b.approval,a.approval);assert.deepEqual(b.memories,a.memories);assert.deepEqual(b.quest,a.quest);assert.deepEqual(b.equipped,a.equipped);assert.deepEqual(b.gear,a.gear);assert.equal(kept.npcs.mara.hp,9);assert(hasCondition(kept,'mara','bleeding'));assert(kept.party.includes('mara'));assert.equal(b.recruited,true);assert.equal(b.left,false);assert.equal(b.hostile,false);assert.equal(placeOf(kept,'mara').room,kept.room,'she travels with the player after a reload');assert(decode(JSON.stringify({...s,companions:{mara:{...a,approval:999}}}))!==null);assert.equal(companionOf(decode(JSON.stringify({...s,companions:{mara:{...a,approval:999}}})),'mara').approval,100,'approval is clamped');assert.equal(blankCompanion('mara').approval,0);});
const supplyRun=()=>{const s=supplied();act(s,'chest','Open');assert(questCarried(s),'the cache is picked up');return s;};
test('Help the Survivors',()=>{const s=supplyRun();const before=s.gold;assert(questActionFor(s,'mara').includes('Hand over the supplies'));act(s,'mara','Hand over the supplies');assert.equal(questState(s),'survivors');assert.equal(standingOf(s,'survivors'),'friendly');assert.equal(standingOf(s,'ratmen'),'suspicious');assert.equal(s.npcs.mara.attitude,'friendly','the quest giver warms up');assert(questCarried(s)===false,'the cache changes hands');assert(s.potions>=8&&s.items.bandages>=1,'the survivors pay in supplies');assert(s.log.some(line=>line.includes('counts it twice')));assert(!questActionFor(s,'mara').length,'the quest closes behind you');assert(factionLine(s,'mara').includes('friendly'));});
test('Help the Ratmen',()=>{const s=supplyRun();assert(questActionFor(s,'rat').includes('Hand over the supplies'));act(s,'rat','Hand over the supplies');assert.equal(questState(s),'ratmen');assert.equal(standingOf(s,'ratmen'),'friendly');assert.equal(standingOf(s,'survivors'),'suspicious');assert.equal(s.npcs.mara.attitude,'neutral','the survivors cool but do not revolt');assert(s.gold>=45,'the ratmen pay in coin');assert(s.items.smokeBombs>=1);assert(s.log.some(line=>line.includes('drag the cache into the dark')));});
test('Betray the faction you promised',()=>{const s=supplied();act(s,'mara','Promise the supplies');assert.equal(s.quests.promised,'survivors');assert.equal(standingOf(s,'survivors'),'friendly','a promise is cheap to start');act(s,'chest','Open');act(s,'rat','Hand over the supplies');assert.equal(questState(s),'ratmen');assert.equal(standingOf(s,'survivors'),'hostile','breaking your word costs more than the promise gained');assert(s.npcs.tobin.memory.lied&&s.npcs.vex.memory.lied,'the whole faction hears about it');assert(s.log.some(line=>line.includes('broke your word'))&&s.log.some(line=>line.includes('find out where the supplies went')));assert(!questActionFor(s,'mara').length,'and no more dialogue about the cache');assert(factionLine(s,'mara').includes('hostile'));});
test('Keep the supplies for yourself',()=>{const s=supplyRun();assert(actions(s,'chest').includes('Keep the supplies'));assert(keepSupplies(s));assert.equal(questState(s),'kept');assert.equal(standingOf(s,'survivors'),'hostile','keeping the cache burns the survivors');assert.equal(standingOf(s,'ratmen'),'hostile','and the ratmen');assert.equal(s.npcs.mara.attitude,'suspicious');assert(s.log.some(line=>line.includes('Neither side is pleased')));assert(!questActionFor(s,'mara').length&&!questActionFor(s,'rat').length);});
test('Standing is per member and the faction averages it',()=>{const s=supplied();act(s,'mara','Talk');act(s,'mara','Help');assert.equal(memberStanding(s,'mara'),'friendly','the individual is won over');assert.equal(standingOf(s,'survivors'),'neutral','one friend does not carry the faction');for(const id of ['tobin','vex']){act(s,id,'Talk');act(s,id,'Help');}assert.equal(standingOf(s,'survivors'),'friendly','all three do');});
test('The faction reacts to violence without owning it',()=>{const s=supplied();approach(s,'rat');interact(s,'rat','Fight');assert.equal(memberStanding(s,'rat'),'hostile','the scrapper takes it personally');assert.equal(standingOf(s,'ratmen'),'suspicious','the pack only hears about it');win(s);assert.equal(standingOf(s,'ratmen'),'hostile','a death is a faction matter');});
test('A friendly faction pays you back once',()=>{const s=supplied();const silver=s.boxes.silver,potions=s.potions;for(const id of ['mara','tobin','vex']){act(s,id,'Talk');act(s,id,'Help');}assert.equal(standingOf(s,'survivors'),'friendly');assert.equal(s.boxes.silver,silver+1,'they share a silver box');assert(s.potions>potions,'and potions');const after=s.boxes.silver;improveStanding(s,'survivors',1,'again');assert.equal(s.boxes.silver,after,'the gift only lands once');});
test('Friendly factions step into your fights',()=>{const s=supplied();act(s,'crate','Break');s.cheese=3;for(const id of ['rat','skulker','brute']){approach(s,id);interact(s,id,'Offer cheese',()=>0.5);}assert.equal(standingOf(s,'ratmen'),'friendly','the whole pack is won over by dairy');approach(s,'tobin');setPlace(s,'rat',s.room,s.x,s.y);interact(s,'tobin','Attack');assert(s.log.some(line=>line.includes('steps in on your side')),'a friendly ratman joins in');assert((s.allies.rat||0)>0);});
test('The ratmen accept a cheese tribute',()=>{const s=supplied();act(s,'crate','Break');const cheese=s.cheese;act(s,'rat','Offer cheese');assert(s.cheese<cheese,'the tribute is paid');assert.equal(memberStanding(s,'rat'),'friendly');assert(s.log.some(line=>line.includes('The ratman accepts')),'the custodian says so');});
test('Faction and quest state survive a save and reload',()=>{const s=supplied();act(s,'rat','Promise the supplies');act(s,'chest','Open');act(s,'mara','Hand over the supplies');assert.equal(questState(s),'survivors');assert.equal(standingOf(s,'ratmen'),'hostile');const kept=checkpoint(s);assert.deepEqual(kept.factions,s.factions);assert.deepEqual(kept.standing,s.standing);assert.deepEqual(kept.quests,s.quests);assert.equal(kept.npcs.rat.memory.lied,true,'the betrayed faction remembers');assert(questActionFor(kept,'mara').length===0&&questActionFor(kept,'rat').length===0);const bad=decode(JSON.stringify({...s,factions:{survivors:'wizard',ratmen:'neutral'}}));assert.equal(bad.factions.survivors,standingOf(s,'survivors'),'bad faction data is recomputed from its members');assert.equal(decode(JSON.stringify({...s,standing:{...s.standing,mara:'nonsense'}})).standing.mara,'neutral','bad standing falls back to neutral');assert.equal(decode(JSON.stringify({...s,quests:{supplies:'nonsense'}})).quests.supplies,'open');assert.equal(STANDING.length,4);assert.equal(FACTIONS.ratmen.members.length,3);assert.equal(factionOf('vex'),'survivors');});
test('Weapon, Armor and Accessory slots take one item each',()=>{const s=supplied();grantedItem(s,'Ratfang Shiv');grantedItem(s,'Last Laugh Boots');grantedItem(s,'Sewer Saint Medal');assert.deepEqual(Object.keys(s.equipped),['weapon','armor','accessory']);assert(equipItem(s,'Ratfang Shiv'));assert.equal(s.equipped.weapon,'Ratfang Shiv');assert.equal(itemSlot('Ratfang Shiv'),'weapon');assert(equipItem(s,'Last Laugh Boots'));assert.equal(s.equipped.armor,'Last Laugh Boots');assert(equipItem(s,'Sewer Saint Medal'));assert.equal(s.equipped.accessory,'Sewer Saint Medal');assert.deepEqual(s.gear,[],'all three items are worn');assert.equal(equippedItems(s).length,3);assert.equal(attackRange(s)[0],6,'weapon bonus applies');assert.equal(abilityBonus(s,'wisdom'),1,'accessory bonus applies');assert(traitOf(s,'lastlaugh')&&traitOf(s,'wounded')&&traitOf(s,'poisonward'));});
test('Equipping a replacement returns the old item to the pack',()=>{const s=supplied();grantedItem(s,'Ratfang Shiv');grantedItem(s,'Iron signet');grantedItem(s,'Lucky charm');equipItem(s,'Ratfang Shiv');equipItem(s,'Iron signet');assert.equal(gearBonus(s,'damage'),2,'weapon plus signet');assert(equipItem(s,'Lucky charm'),'the accessory slot swaps');assert.equal(s.equipped.accessory,'Lucky charm');assert.deepEqual(s.gear,['Iron signet'],'the replaced item goes back to the pack');assert.equal(gearBonus(s,'damage'),1,'the signet damage stops applying');assert.equal(gearBonus(s,'checks'),1,'and the charm starts');assert(s.log.some(line=>line.includes('Iron signet returns to your pack')));assert(unequipItem(s,'Lucky charm'));assert.equal(s.equipped.accessory,null);assert(s.gear.includes('Lucky charm'));assert.equal(gearBonus(s,'checks'),0,'stowing removes the bonus too');assert(!unequipItem(s,'Lucky charm'),'it cannot be stowed twice');});test('Only equipped traits are active',()=>{const s=supplied();grantedItem(s,'Last Laugh Boots');assert(!traitOf(s,'lastlaugh'),'owning an item does not switch its trait on');assert(equipItem(s,'Last Laugh Boots'));assert(traitOf(s,'lastlaugh'),'wearing it does');assert(unequipItem(s,'Last Laugh Boots'));assert(!traitOf(s,'lastlaugh'),'and stowing it switches the trait off again');});test('Three slots survive a save and reload',()=>{const s=supplied();grantedItem(s,'Ratfang Shiv');grantedItem(s,'Last Laugh Boots');grantedItem(s,'Sewer Saint Medal');grantedItem(s,'Iron signet');for(const name of ['Ratfang Shiv','Last Laugh Boots','Sewer Saint Medal'])equipItem(s,name);const kept=checkpoint(s);assert.deepEqual(kept.equipped,{weapon:'Ratfang Shiv',armor:'Last Laugh Boots',accessory:'Sewer Saint Medal'});assert.deepEqual(kept.gear,['Iron signet']);assert.equal(gearBonus(kept,'damage'),1);assert.equal(abilityBonus(kept,'wisdom'),1);assert(traitOf(kept,'lastlaugh')&&traitOf(kept,'wounded'));assert.equal(itemOf('Last Laugh Boots').traitName,'Second Wind');assert.equal(itemOf('Last Laugh Boots').traitText,'When damage leaves you below 20% HP, gain a temporary movement bonus.');const swapped=decode(JSON.stringify({...kept,equipped:{weapon:'Last Laugh Boots',armor:null,accessory:null}}));assert.equal(swapped.equipped.weapon,null,'an item in the wrong slot is dropped');assert(swapped.gear.includes('Last Laugh Boots'),'and returned to the pack');});
test('Equipping an Uncommon item applies its effects',()=>{const s=supplied();grantedItem(s,'Ratfang Shiv');assert.equal(rarityOf('Ratfang Shiv'),'uncommon');assert.equal(s.equipped.weapon,null,'new items are stowed, not worn');assert(equipItem(s,'Ratfang Shiv'));assert.equal(s.equipped.weapon,'Ratfang Shiv');assert.equal(attackRange(s)[0],6,'the shiv adds its damage');approach(s,'rat');interact(s,'rat','Fight');s.npcs.rat.hp=5;fight(s,'Attack',()=>0.5);assert(s.log.some(line=>line.includes('the wound makes the opening')),'the wounded trait fires against a hurt enemy');assert.equal(s.npcs.rat.hp,0,'1d3+5 damage plus the trait finishes 5 HP');});
test('Equipping a Rare item applies its effects',()=>{const s=supplied();grantedItem(s,'Sewer Saint Medal');assert.equal(rarityOf('Sewer Saint Medal'),'rare');equipItem(s,'Sewer Saint Medal');assert.equal(abilityBonus(s,'wisdom'),1);assert.equal(s.equipped.accessory,'Sewer Saint Medal');assert.equal(character(s).abilities.wisdom,s.abilities.wisdom+1,'the medal raises Wisdom for every check');const wise=check({actor:character(s),skill:'perception',dc:12,rng:()=>0.5});const plain=check({actor:character(fresh()),skill:'perception',dc:12,rng:()=>0.5});assert.equal(wise.total,plain.total+1,'and the bonus lands on the roll');assert(traitOf(s,'poisonward'));const kept=checkpoint(s);assert.equal(abilityBonus(kept,'wisdom'),1,'the medal survives a save');});
test('Special traits change how a fight plays out',()=>{const boots=supplied();grantedItem(boots,'Last Laugh Boots');equipItem(boots,'Last Laugh Boots');approach(boots,'rat');interact(boots,'rat','Fight');boots.hp=8;fight(boots,'Attack',()=>0.999);assert.equal(boots.hp,5,'the hit lands');assert(boots.log.some(line=>line.includes('somewhere to be')),'the boots notice');assert.equal(boots.flags.lastLaugh,true);fight(boots,'Back off',()=>0.5);assert(boots.log.some(line=>line.includes('You fall back to range 3')),'the burst covers two bands at once');assert(!boots.flags.lastLaugh,'and is spent');const grip=supplied();grantedItem(grip,'Improviser’s Grip');assert.equal(rarityOf('Improviser’s Grip'),'epic');equipItem(grip,'Improviser’s Grip');approach(grip,'rat');interact(grip,'rat','Fight');fight(grip,'Throw a rock',()=>0.999);assert.equal(grip.npcs.rat.hp,6,'thrown objects hit for 4+2 with the grip');});
test('Box rarity weighting follows the tier',()=>{const sample=(tier,rolls)=>{const counts={};for(let i=0;i<rolls;i++){const s=fresh();s.boxes[tier]=1;const rolled=openRewardBox(s,tier,seeded(i+1));const key=rolled.rarity||'common';counts[key]=(counts[key]||0)+1;}return counts;};
 const share=(counts,key)=>((counts[key]||0)/400);
 const bronze=sample('bronze',400);assert(share(bronze,'uncommon')<0.2,'bronze rarely coughs up an uncommon');assert(!bronze.rare&&!bronze.epic,'never above uncommon');
 const silver=sample('silver',400);assert(share(silver,'uncommon')>0.4&&share(silver,'rare')>0.1,'silver is mostly uncommon with some rare');assert(!silver.epic,'and never epic');
 const gold=sample('gold',400);assert(share(gold,'rare')>0.6,'gold is mostly rare');assert(share(gold,'epic')>0.05&&share(gold,'epic')<0.2,'with a small epic chance');assert(!gold.uncommon&&!gold.common,'and nothing common');});
test('Gear, rarity and traits survive a save and reload',()=>{const s=supplied();grantedItem(s,'Ratfang Shiv');grantedItem(s,'Sewer Saint Medal');grantedItem(s,'Last Laugh Boots');equipItem(s,'Ratfang Shiv');equipItem(s,'Sewer Saint Medal');const kept=checkpoint(s);assert.deepEqual(kept.equipped,{weapon:'Ratfang Shiv',armor:null,accessory:'Sewer Saint Medal'});assert.deepEqual(kept.gear,['Last Laugh Boots']);assert.equal(gearBonus(kept,'damage'),1,'equipped damage is saved');assert.equal(abilityBonus(kept,'wisdom'),1,'and so is the ability bonus');assert(traitOf(kept,'wounded')&&traitOf(kept,'poisonward'));assert.equal(kept.gear.includes('Nonsense'),false);const junk=decode(JSON.stringify({...s,gear:['Nonsense'],accessories:['Also nonsense']}));assert.deepEqual(junk.gear,[]);assert.deepEqual(junk.equipped,{weapon:'Ratfang Shiv',armor:null,accessory:'Sewer Saint Medal'},'unknown legacy names are dropped, valid slots survive');});
const boxRun=(tier)=>{const s=fresh();s.gold=30;s.potions=6;s.boxes[tier]=1;return s;};
test('Bronze, Silver and Gold boxes roll their own tables',()=>{const bronze=boxRun('bronze');assert(isSafeRoom(bronze),'Intake is the safe room');const rolled=openRewardBox(bronze,'bronze',()=>0.99);assert(rolled.ok);assert.equal(rolled.reward,'Ratfang Shiv','a high roll reaches the rare end of the bronze table');assert.deepEqual(bronze.gear,['Ratfang Shiv'],'the item lands in the pack unopened-but-owned');assert.equal(bronze.boxes.bronze,0,'opening consumes the box');assert(bronze.log.some(line=>line.includes('bronze box:'))&&bronze.log.some(line=>line.includes('anything with a point on it')),'the AI line is logged');const silver=boxRun('silver');const srolled=openRewardBox(silver,'silver',()=>0.99);assert.equal(srolled.rarity,'rare','the top of the silver table is rare');assert(silver.log.some(line=>line.includes('silver box: rare Last Laugh Boots')));const gold=boxRun('gold');gold.pending=0;openRewardBox(gold,'gold',()=>0);assert.deepEqual(gold.gear,['Iron signet'],'gold opens on a rare accessory');const epic=boxRun('gold');const erolled=openRewardBox(epic,'gold',()=>0.99);assert.equal(erolled.rarity,'epic','and the tail of the table is epic');assert.deepEqual(epic.gear,['Improviser’s Grip']);const token=boxRun('gold');const pending=token.pending;openRewardBox(token,'gold',()=>0.8);assert.equal(token.pending,pending+1,'the class-related token grants a stat choice');assert(token.log.some(line=>line.includes('Somebody believes in you')));});
test('Boxes only open in a safe room and never in combat',()=>{const s=boxRun('bronze');s.room=1;assert.equal(isSafeRoom(s),false);assert.deepEqual(openRewardBox(s,'bronze'),{ok:false,reason:'unsafe'});assert.equal(s.boxes.bronze,1,'a refused box stays unopened');assert(!s.log.some(line=>line.includes('bronze box:')));setPlace(s,'rat',0,4,5);s.room=0;s.x=4;s.y=6;interact(s,'rat','Fight');assert(s.combat,'the fight is on');assert.equal(openRewardBox(s,'bronze').reason,'busy');assert.equal(s.boxes.bronze,1);});
test('Boxes, rewards and accessories survive a save',()=>{const s=fresh();s.boxes.bronze=2;s.boxes.gold=1;openRewardBox(s,'gold',()=>0.99);assert.deepEqual(s.equipped,emptyEquipped(),'a fresh crawler has nothing worn');grantedItem(s,'Lucky charm');equipItem(s,'Lucky charm');const kept=checkpoint(s);assert.equal(kept.boxes.bronze,2,'unopened boxes are saved');assert.equal(kept.boxes.gold,0,'an opened box is gone for good');assert.equal(kept.equipped.accessory,'Lucky charm','worn gear is saved');const check1=check({actor:character(kept),skill:'stealth',dc:10,modifiers:gearBonus(kept,'checks'),rng:()=>0.5});const plain=check({actor:character(fresh()),skill:'stealth',dc:10,rng:()=>0.5});assert.equal(check1.total,plain.total+1,'the lucky charm reaches checks');assert.equal(gearBonus(kept,'checks'),1);const legacy=decode(JSON.stringify({...s,boxes:3}));assert.equal(legacy.boxes.bronze,3,'old numeric boxes become bronze');assert.equal(legacy.boxes.gold,0);assert.equal(decode(JSON.stringify({...s,boxes:{bronze:-1,silver:0,gold:0}})).boxes.bronze,0,'bad counts are reset');const legacyJunk=decode(JSON.stringify({...s,accessories:['Nonsense']}));assert.equal(legacyJunk.equipped.accessory,'Lucky charm','a stray legacy name cannot displace worn gear');assert.deepEqual(legacyJunk.gear,['Improviser’s Grip'],'the pack survives a stray legacy name');});
test('Achievement box rewards are tiered and paid once',()=>{const s=fresh();assert.equal(achievementFor('First Blood').tier,'bronze');assert.equal(achievementFor('Terminal Optimism').tier,'gold');assert.equal(achievementFor('People person').tier,'silver');award(s,'First Blood');assert.equal(s.boxes.bronze,1);award(s,'First Blood');assert.equal(s.boxes.bronze,1,'the same achievement cannot pay twice');award(s,'Terminal Optimism');award(s,'People person');assert.deepEqual(s.boxes,{bronze:1,silver:1,gold:1});assert(BOX_TIERS.every(tier=>BOX_LOOT[tier].length>=5),'each tier has a real table');assert(Object.values(ITEMS).every(item=>RARITIES.includes(item.rarity)&&item.description&&item.type),'every item has rarity, type and description');});
test('A straight fight unlocks the fighting achievements',()=>{const s=supplied();assert(!s.achievements.includes('First Blood'));approach(s,'rat');interact(s,'rat','Fight');win(s);assert(s.achievements.includes('First Blood'),'first kill is logged');assert(s.log.some(line=>line.includes('NEW ACHIEVEMENT: First Blood'))&&s.log.some(line=>line.includes('It was not you')));const clever=supplied();approach(clever,'rat');interact(clever,'rat','Fight');let guard=0;while(clever.combat&&guard++<20)fight(clever,'Throw a rock',()=>0.999);assert(clever.achievements.includes('Hands Off'),'winning with thrown rocks counts as no normal attack');assert(!clever.achievements.includes('Occupational Hazard'),'that is not an environmental kill');});
test('Environmental play unlocks its own achievements',()=>{const s=supplied();approach(s,'rat');interact(s,'rat','Fight');fight(s,'Tip the brazier',()=>0.5);s.npcs.rat.hp=2;fight(s,'Defend',()=>0.5);assert(!s.combat,'the fire finished it');assert(s.achievements.includes('Occupational Hazard'));assert(s.log.some(line=>line.includes('workplace safety')));const outnumbered=supplied();outnumbered.maxHp=200;outnumbered.hp=200;setPlace(outnumbered,'rat',3,9,5);setPlace(outnumbered,'brute',3,8,5);outnumbered.room=3;outnumbered.x=10;outnumbered.y=5;interact(outnumbered,'rat','Fight');assert.equal(outnumbered.combat.enemies.length,2);let guard=0;while(outnumbered.combat&&guard++<60)fight(outnumbered,'Attack',()=>0.999);assert(outnumbered.achievements.includes('Pack Tactics'),'beating two at once is logged');});
test('Thieving play unlocks both sides of the coin',()=>{const quiet=supplied();act(quiet,'tobin','Talk');act(quiet,'tobin','Lie');act(quiet,'tobin','Pickpocket');assert(quiet.achievements.includes('Five-Finger Discount'),'a clean theft pays');assert(!quiet.achievements.includes('Sticky Fingers'));travel(quiet,2);assert(quiet.achievements.includes('Sticky Fingers'),'and the discovery is logged too');const caught=supplied();approach(caught,'tobin');interact(caught,'tobin','Pickpocket',()=>0);assert(caught.npcs.tobin.memory.theftAttempt);assert(caught.achievements.includes('Sticky Fingers'));});
test('Betrayal, desperation and once-only rewards',()=>{const traitor=recruitMara(supplied());act(traitor,'mara','Attack');assert(traitor.achievements.includes('Severance Package'));assert(traitor.log.some(line=>line.includes('retirement plan')));const desperate=supplied();approach(desperate,'rat');interact(desperate,'rat','Fight');desperate.level=10;desperate.hp=7;desperate.npcs.rat.hp=3;fight(desperate,'Throw a rock',()=>0.999);assert(!desperate.combat,'the last throw finishes it');assert(desperate.achievements.includes('Terminal Optimism'),'winning at deaths door is logged');const once=fresh();const boxes=once.boxes.bronze;award(once,'First Blood');const after=once.achievements.length;award(once,'First Blood');assert.equal(once.achievements.length,after,'an achievement cannot be earned twice');assert.equal(once.boxes.bronze,boxes+1,'the reward is paid once');const xp=once.xp;award(once,'Hands Off');assert(once.xp>xp,'an XP reward pays bonus experience');const kept=checkpoint(once);assert(kept.achievements.includes('First Blood')&&kept.achievements.includes('Hands Off'));assert.equal(achievementFor('First Blood').reward,'box');assert.equal(achievementFor('Hands Off').reward,'xp');assert(ACHIEVEMENTS['Occupational Hazard'].condition.includes('burning'));});
test('Playstyle decides which classes are offered',()=>{const brawler=fresh();for(let i=0;i<6;i++)recordDeed(brawler,'melee');assert(classReady(brawler),'enough deeds opens the event');assert(classOptions(brawler).includes('bruiser'));const thief=fresh();for(let i=0;i<3;i++){recordDeed(thief,'stealth');recordDeed(thief,'theft');}assert(classOptions(thief).includes('rogue'));assert.notDeepEqual(classOptions(brawler),classOptions(thief),'different habits offer different paths');const trapper=fresh();for(let i=0;i<3;i++){recordDeed(trapper,'fire');recordDeed(trapper,'environment');}assert(classOptions(trapper).includes('trapper'));assert.equal(classOptions(fresh()).length,3,'a fresh crawler still sees three options');assert.equal(RACES[fresh().race].name,'Human','the first build keeps everyone Human');});
test('Choosing a class applies its bonuses immediately',()=>{const bruiser=fresh();for(let i=0;i<6;i++)recordDeed(bruiser,'melee');assert.equal(attackRange(bruiser)[0],5,'no bonus before specialising');assert(chooseClass(bruiser,'bruiser'));assert.equal(bruiser.class,'bruiser');assert.equal(attackRange(bruiser)[0],7,'the bruiser hits harder');assert.equal(attackRange(bruiser)[1],9);const warden=fresh();for(let i=0;i<6;i++)recordDeed(warden,'help');assert(chooseClass(warden,'warden'));assert.equal(warden.maxHp,35,'the warden brings extra maximum HP');const rogue=fresh();rogue.class='rogue';const sly=check({actor:character(rogue),skill:'stealth',dc:10,modifiers:2,rng:()=>0.5});const plain=check({actor:character(fresh()),skill:'stealth',dc:10,rng:()=>0.5});assert.equal(sly.total,plain.total+2,'the rogue bonus reaches checks');assert(!chooseClass(bruiser,'rogue'),'a class can only be chosen once');});
test('Class abilities appear in combat and are spent',()=>{const s=supplied();for(let i=0;i<6;i++)recordDeed(s,'melee');chooseClass(s,'bruiser');act(s,'rat','Fight');assert(combatActions(s).includes('Cleave'),'the active ability is offered');assert(abilityReady(s));const before=s.npcs.rat.hp;fight(s,'Cleave',()=>0.5);assert(s.npcs.rat.hp<=before-9,'cleave hits much harder than a normal swing');assert(!combatActions(s).includes('Cleave'),'and is spent for the fight');assert(!abilityReady(s));assert(activeAbility(s)==='Cleave');});
test('Class and deeds save and reload, and drive later checks',()=>{const s=fresh();for(let i=0;i<4;i++)recordDeed(s,'stealth');recordDeed(s,'theft');recordDeed(s,'theft');chooseClass(s,'rogue');s.abilities.dexterity=18;const kept=checkpoint(s);assert.equal(kept.class,'rogue');assert.equal(kept.race,'human');assert.equal(kept.classOffered,true);assert.equal(kept.deeds.stealth,4);assert.equal(kept.deeds.theft,2);assert.equal(check({actor:character(kept),skill:'sleight of hand',dc:14,modifiers:2,rng:()=>0.5}).total,check({actor:character(kept),skill:'sleight of hand',dc:14,rng:()=>0.5}).total+2,'the reloaded class still adds its bonus');assert.equal(decode(JSON.stringify({...s,class:'wizard'})).class,'crawler','an unknown class falls back to Crawler');assert.equal(decode(JSON.stringify({...s,deeds:{melee:-1}})).deeds.melee,0,'bad deed counts are reset');});
test('Changing combat intent is free; smoke escapes without damage; injuries persist',()=>{let s=fresh();s.items.smokeBombs=1;act(s,'vex','Attack');const hp=s.hp;fight(s,'Switch to nonlethal');assert.equal(s.hp,hp);assert(combatActions(s).includes('Switch to lethal'));fight(s,'Attack',()=>.5);const before=s.hp,enemyHP=s.npcs.vex.hp;fight(s,'Smoke bomb');assert.equal(s.hp,before);assert.equal(s.items.smokeBombs,0);assert.equal(s.combat,null);s=checkpoint(s);assert.equal(s.npcs.vex.hp,enemyHP);assert(s.npcs.vex.memory.attacked);});
test('Looted items have actual uses and cannot be used twice',()=>{const s=fresh();s.hp=10;assert(useBandage(s));assert.equal(s.hp,16);assert(!useBandage(s));s.items.whetstones=1;assert(useWhetstone(s));assert.deepEqual(attackRange(s),[6,8]);assert(!useWhetstone(s));s.flags.vexTraining=true;assert.deepEqual(attackRange(s),[7,9]);});
test('Tobin information reveals a separate one-time cache reward',()=>{const s=supplied();act(s,'pipe','Search');const first=s.gold;act(s,'tobin','Talk');act(s,'tobin','Help');act(s,'tobin','Befriend');act(s,'pipe','Search');assert.equal(s.gold,first+3);const after=s.gold;act(s,'pipe','Search');assert.equal(s.gold,after);checkpoint(s);});
test('Old saves migrate attitudes, deaths and inventories without reviving anyone',()=>{let old={...fresh(),version:1,npcs:{mara:{hp:0,state:'dead'},rat:{hp:0,state:'dead'}},flags:{stolen:true,looted:true},key:true,room:1,x:6,y:6};delete old.items;delete old.logSerial;const s=decode(JSON.stringify(old));assert(s);assert.equal(s.version,2);assert.equal(s.npcs.mara.condition,'dead');assert.equal(s.npcs.rat.condition,'dead');assert(s.npcs.mara.memory.looted);assert.equal(s.npcs.mara.inventory.gold,0);assert(!blocked(s,s.x,s.y));assert.equal(s.npcs.tobin.attitude,'suspicious');});
test('Malformed saves fail safely; unconscious and completed saves round-trip',()=>{let s=fresh();for(const raw of ['nope','null','{}',JSON.stringify({...s,hp:0}),JSON.stringify({...s,npcs:null}),JSON.stringify({...s,x:4,y:3}),JSON.stringify({...s,items:null}),JSON.stringify({...s,npcs:{...s.npcs,vex:{...s.npcs.vex,condition:'dead'}}})])assert.equal(decode(raw),null);getKey(s);finish(s);assert(decode(encode(s)).complete);});

function summary(s){return {complete:s.complete,hp:s.hp,gold:s.gold,potions:s.potions,items:s.items,damage:attackRange(s),achievements:s.achievements,npcs:Object.fromEntries(PEOPLE.map(id=>[id,s.npcs[id]]))};}
function helpful(){let s=fresh();act(s,'chest','Open');act(s,'note','Read');for(const id of ['tobin','mara']){act(s,id,'Talk');act(s,id,'Help');act(s,id,'Befriend');act(s,id,'Trade');s=checkpoint(s);}act(s,'crate','Break');act(s,'rat','Offer cheese');act(s,'pipe','Search');act(s,'vex','Talk');act(s,'vex','Help');act(s,'vex','Befriend');act(s,'vex','Trade');useWhetstone(s);s=finish(s);for(const id of PEOPLE){assert.equal(s.npcs[id].attitude,'friendly');assert.equal(s.npcs[id].condition,'conscious');}assert.deepEqual(attackRange(s),[7,9]);return s;}
function thief(){let s=fresh();act(s,'chest','Open');act(s,'note','Read');act(s,'tobin','Talk');act(s,'tobin','Lie');act(s,'tobin','Trade');act(s,'tobin','Pickpocket');act(s,'mara','Talk');act(s,'mara','Help');act(s,'mara','Befriend');act(s,'mara','Lie');act(s,'mara','Pickpocket');s=checkpoint(s);act(s,'vex','Talk');assert(!s.npcs.vex.memory.sawTheft,'Vex was in another room and cannot know about the thefts');assert(!s.npcs.vex.memory.sawRob);act(s,'vex','Lie');act(s,'vex','Pickpocket');travel(s,3);travel(s,4);useWhetstone(s);s=finish(s);for(const id of PEOPLE){assert.equal(s.npcs[id].attitude,'hostile');assert.equal(s.npcs[id].condition,'conscious');assert(s.npcs[id].memory.theftDetected);}assert(s.npcs.mara.memory.betrayed);return s;}
function violent(){let s=fresh();act(s,'chest','Open');act(s,'tobin','Rob openly');act(s,'tobin','Knock unconscious');win(s);act(s,'tobin','Loot');act(s,'tobin','Kill');s=checkpoint(s);for(const id of ['mara','vex']){act(s,'fountain','Heal');act(s,id,'Attack');win(s);act(s,id,'Loot');s=checkpoint(s);}useWhetstone(s);s=finish(s);for(const id of PEOPLE){assert.equal(s.npcs[id].condition,'dead');assert(s.npcs[id].memory.killed);assert(STOCK_KEYS.every(k=>s.npcs[id].inventory[k]===0));}assert(!s.npcs.vex.memory.sawKill,'Vex was elsewhere and did not see Tobin die');return s;}
const report={};
test('Full helpful playthrough: three allies, information rewards and stronger attacks',()=>report.helpful=summary(helpful()));
test('Full manipulative playthrough: successful thefts, exposed reputation and betrayal',()=>report.thief=summary(thief()));
test('Full violent playthrough: all three dead, empty inventories, exit remains usable',()=>report.violent=summary(violent()));
test('The three completed saves produce noticeably different end states',()=>{assert.notDeepEqual(report.helpful,report.thief);assert.notDeepEqual(report.thief,report.violent);assert.notDeepEqual(report.helpful,report.violent);assert(report.helpful.damage[0]>report.thief.damage[0]);assert(report.violent.gold>report.helpful.gold);});
function holdHarness(){let pending=new Map(),id=0,steps=[],allowed=true;class Pad extends EventTarget{disabled=false;dataset={move:'1,0'};classList={add(){},remove(){}};setPointerCapture(){}}const button=new Pad(),other=new Pad();other.dataset.move='0,-1';const controls=bindHoldControls([button,other],{move:(...p)=>steps.push(p),canMove:()=>allowed,setTimer:(fn,delay)=>{pending.set(++id,{fn,delay});return id;},clearTimer:id=>pending.delete(id)});const fire=(type,props={},target=button)=>{const e=new Event(type,{cancelable:true});Object.assign(e,{pointerId:1,...props});target.dispatchEvent(e);};return {button,other,controls,steps,fire,pending,lock:()=>allowed=false,tick:()=>{const [id,{fn,delay}]=pending.entries().next().value;pending.delete(id);fn();return delay;}};}
test('Touch hold repeats and release stops; click does not double-step',()=>{const h=holdHarness();h.fire('pointerdown');assert.equal(h.steps.length,1);assert.equal(h.tick(),270);assert.equal(h.tick(),165);assert.equal(h.steps.length,3);h.fire('pointerup');h.fire('click',{detail:1});assert.equal(h.steps.length,3);assert.equal(h.pending.size,0);h.fire('click',{detail:0});assert.equal(h.steps.length,4);});
test('Cancelled touches and app pause stop held movement',()=>{const h=holdHarness();for(const type of ['pointercancel','lostpointercapture']){h.fire('pointerdown');h.fire(type);assert.equal(h.pending.size,0);}h.fire('pointerdown');h.controls.stop();assert.equal(h.pending.size,0);h.fire('pointerdown');h.lock();h.tick();assert.equal(h.pending.size,0);});
test('Only the active finger owns direction and disabled controls do not move',()=>{const h=holdHarness();h.fire('pointerdown');h.fire('pointerdown',{pointerId:2},h.other);h.fire('pointerup',{pointerId:1});h.tick();assert.deepEqual(h.steps.at(-1),[0,-1]);h.fire('pointerup',{pointerId:2},h.other);assert.equal(h.pending.size,0);h.button.disabled=true;const before=h.steps.length;h.fire('pointerdown');h.fire('click',{detail:0});assert.equal(h.steps.length,before);});

const fixed=(...values)=>{let index=0;return()=>values[Math.min(index++,values.length-1)];};
test('Ability scores convert to the standard modifiers',()=>{assert.equal(modifier(16),3);assert.equal(modifier(15),2);assert.equal(modifier(10),0);assert.equal(modifier(8),-1);assert.equal(modifier(1),-5);assert.equal(modifier(20),5);assert.equal(proficiencyBonus(1),2);assert.equal(proficiencyBonus(5),3);assert.equal(Object.keys(SKILLS).length,18);assert.equal(ABILITIES.length,6);assert.equal(character(fresh(),'vex').abilities.strength,17);});
test('Stealth check uses Dexterity and the character proficiency',()=>{const s=fresh();const r=check({actor:character(s),skill:'stealth',dc:12,rng:fixed(0.5)});assert.equal(r.kind,'skill');assert.equal(r.ability,'dexterity');assert.equal(r.rawRoll,11);assert.equal(r.abilityModifier,3);assert.equal(r.proficiency,true);assert.equal(r.proficiencyBonus,2);assert.equal(r.total,16);assert.equal(r.dc,12);assert.equal(r.success,true);});
test('Sleight of Hand check matches the worked example',()=>{const win=check({score:16,skill:'sleight of hand',dc:14,proficient:true,rng:fixed(0.5)});assert.equal(win.rawRoll,11);assert.equal(win.abilityModifier,3);assert.equal(win.proficiencyBonus,2);assert.equal(win.total,16);assert.equal(win.success,true);const lose=check({score:16,skill:'sleight of hand',dc:14,proficient:true,rng:fixed(0)});assert.equal(lose.rawRoll,1);assert.equal(lose.total,6);assert.equal(lose.success,false);});
test('Persuasion check omits proficiency the character lacks',()=>{const s=fresh();const r=check({actor:character(s),skill:'persuasion',dc:13,rng:fixed(0.5)});assert.equal(r.ability,'charisma');assert.equal(r.abilityModifier,2);assert.equal(r.proficiency,false);assert.equal(r.total,13);assert.equal(r.success,true);});
test('Intimidation check adds proficiency when it applies',()=>{const s=fresh();const r=check({actor:character(s),skill:'intimidation',dc:15,proficient:true,rng:fixed(0.5)});assert.equal(r.ability,'charisma');assert.equal(r.proficiency,true);assert.equal(r.otherModifiers,0);assert.equal(r.total,15);assert.equal(r.success,true);});
test('Perception check uses Wisdom and includes extra modifiers',()=>{const s=fresh();const r=check({actor:character(s),skill:'perception',dc:18,modifiers:[2,-1],rng:fixed(0.5)});assert.equal(r.ability,'wisdom');assert.equal(r.abilityModifier,1);assert.equal(r.otherModifiers,1);assert.equal(r.total,15);assert.equal(r.success,false);});
test('Saving throws use the character save proficiencies',()=>{const s=fresh();const dex=check({actor:character(s),ability:'dexterity',save:true,dc:13,rng:fixed(0.5)});assert.equal(dex.kind,'save');assert.equal(dex.proficiency,true);assert.equal(dex.total,16);assert.equal(dex.success,true);const con=check({actor:character(s),ability:'constitution',save:true,dc:13,rng:fixed(0.5)});assert.equal(con.proficiency,false);assert.equal(con.total,13);assert.equal(con.success,true);});
test('Advantage keeps the higher die, disadvantage the lower, and they cancel',()=>{const actor=character(fresh());const adv=check({actor,skill:'stealth',advantage:true,rng:fixed(0.1,0.9)});assert.deepEqual(adv.rolls,[3,19]);assert.equal(adv.rawRoll,19);assert.equal(adv.advantage,true);assert.equal(adv.disadvantage,false);const dis=check({actor,skill:'stealth',disadvantage:true,rng:fixed(0.1,0.9)});assert.equal(dis.rawRoll,3);assert.equal(dis.disadvantage,true);const both=check({actor,skill:'stealth',advantage:true,disadvantage:true,rng:fixed(0.5,0.9)});assert.equal(both.rolls.length,1);assert.equal(both.rawRoll,11);assert.equal(both.advantage,false);assert.equal(both.disadvantage,false);});
test('Characters keep abilities through a save and old saves gain the defaults',()=>{const s=fresh();const kept=checkpoint(s);assert.deepEqual(kept.abilities,s.abilities);assert.deepEqual(kept.skills,s.skills);const old={...fresh()};delete old.abilities;delete old.skills;delete old.saves;delete old.level;const restored=decode(JSON.stringify(old));assert(restored);assert.deepEqual(restored.abilities,s.abilities);assert.deepEqual(restored.skills,s.skills);assert.equal(restored.level,1);});
function quotedList(source,pattern){const block=source.match(pattern);assert(block,`Could not find a list to read: ${pattern}`);return block[1].split(',').map(part=>part.trim()).filter(part=>part.startsWith("'")).map(part=>part.slice(1,-1));}
const swSource=readFileSync('sw.js','utf8');
const swCache=swSource.match(/CACHE = '([^']+)'/)[1];
const buildSource=readFileSync('build.mjs','utf8');
const shipped=quotedList(buildSource,/for\(const file of \[([\s\S]*?)\]\)/);
const precached=quotedList(swSource,/const ASSETS = \[([\s\S]*?)\];/);
const normalise=path=>path.replace(/^\.\//,'');

test('The offline precache covers every file the build ships, and each one exists',()=>{
 assert(precached.includes('./'),'A directory launch must be precached for Home Screen starts');
 assert(existsSync('sw.js'));
 // sw.js is deliberately absent: the browser keeps its own copy of the worker.
 for(const file of shipped.filter(file=>file!=='sw.js'))assert(precached.map(normalise).includes(file),`${file} ships but is never precached`);
 for(const asset of precached.map(normalise).filter(Boolean))assert(existsSync(asset),`${asset} is precached but missing from the repository`);
});

test('The service worker is registered, served as JavaScript, and cache-versioned',()=>{
 assert(readFileSync('src/app.mjs','utf8').includes("register('sw.js')"),'The app must register the service worker');
 assert(/\.js'\s*:\s*'text\/javascript'/.test(readFileSync('server.mjs','utf8')),'The dev server must serve .js as JavaScript or browsers refuse the worker');
 assert(/CACHE = '[^']+'/.test(swSource),'The cache name must be versioned so releases can replace it');
 assert(swSource.includes('caches.delete'),'Old caches must be cleaned up on activation');
 assert(swSource.includes("request.mode === 'navigate'"),'Navigations need a shell fallback when the network is gone');
 assert(swSource.includes('request.method !== \'GET\''),'Only GET requests may be intercepted');
});

test('Offline play leaves gameplay and save rules untouched',()=>{const s=fresh();getKey(s);finish(s);assert.equal(s.hp,30);assert(decode(encode(fresh())).version,2);});

// The service worker is exercised directly, with a stubbed Cache API and
// fetch, so the offline path is tested rather than only inspected.
function workerHarness(){
 const base='http://localhost:4173/';
 const listeners={},stores=new Map();
 let online=true;
 const url=req=>new URL(typeof req==='string'?req:req.url,base).href;
 const response=href=>({url:href,ok:true,type:'basic',clone(){return this;}});
 const store=name=>{if(!stores.has(name))stores.set(name,new Map());return stores.get(name);};
 const caches={open:async name=>{const map=store(name);return{addAll:async urls=>{if(!online)throw new Error('offline');for(const item of urls)map.set(url(item),response(url(item)));},put:async(req,res)=>map.set(url(req),res),match:async req=>map.get(url(req))};},keys:async()=>[...stores.keys()],delete:async name=>stores.delete(name),match:async req=>{for(const map of stores.values()){const hit=map.get(url(req));if(hit)return hit;}return undefined;}};
 const selfStub={location:{origin:'http://localhost:4173'},claimed:false,skipWaiting:async()=>{},clients:{claim:async()=>{selfStub.claimed=true;}},addEventListener:(type,fn)=>{listeners[type]=fn;}};
 new Function('self','caches','fetch',readFileSync('sw.js','utf8'))(selfStub,caches,async req=>{if(!online)throw new Error('network down');return response(url(req));});
 return {selfStub,stores,store,response,url,listeners,setOnline:value=>{online=value;},async fire(type,event={}){const waits=[],responded=[];listeners[type]({...event,waitUntil:p=>waits.push(p),respondWith:p=>responded.push(p)});await Promise.all(waits);return {responded,settled:responded.length?Promise.all(responded):null};}};
}
const get=url=>({method:'GET',url,mode:'no-cors'});
const navigate=url=>({method:'GET',url,mode:'navigate'});

test('The worker precaches the whole shell, then clears stale caches and takes control',async()=>{
 const h=workerHarness();
 h.store('dungeoncrawlers-v0').set('http://localhost:4173/old.js',h.response('http://localhost:4173/old.js'));
 await h.fire('install');
 const cached=h.store(swCache);
 for(const asset of precached){const href=h.url(asset);assert(cached.has(href),`install did not precache ${asset}`);assert.equal(cached.get(href).ok,true);}
 await h.fire('activate');
 assert.equal(h.stores.has('dungeoncrawlers-v0'),false,'the previous cache version must be removed');
 assert(h.selfStub.claimed,'the worker must claim open pages so the first visit becomes offline-capable');
});

test('Network-first serving falls back to the cache, then to the shell for navigations',async()=>{
 const h=workerHarness();
 await h.fire('install');
 const online=await h.fire('fetch',{request:get('http://localhost:4173/style.css')});
 assert.equal(online.responded.length,1,'a same-origin GET must be answered by the worker');
 const live=await online.responded[0];
 assert.equal(live.url,'http://localhost:4173/style.css');
 assert(h.store(swCache).has('http://localhost:4173/style.css'),'a successful response must be cached for later');
 h.store(swCache).set('http://localhost:4173/style.css',h.response('http://localhost:4173/style.css?cached'));
 h.setOnline(false);
 const offline=await h.fire('fetch',{request:get('http://localhost:4173/style.css')});
 assert.equal((await offline.responded[0]).url,'http://localhost:4173/style.css?cached','offline requests must be served from the cache');
 const deep=await h.fire('fetch',{request:navigate('http://localhost:4173/some/home/screen/start')});
 assert.equal((await deep.responded[0]).url,'http://localhost:4173/index.html','an uncached navigation must fall back to the game shell');
});

test('Non-GET and cross-origin requests are left alone',async()=>{
 const h=workerHarness();
 await h.fire('install');
 const post=await h.fire('fetch',{request:{method:'POST',url:'http://localhost:4173/save',mode:'no-cors'}});
 const font=await h.fire('fetch',{request:get('https://fonts.example.com/display.css')});
 assert.equal(post.responded.length,0);
 assert.equal(font.responded.length,0);
});

await Promise.all(pending);console.log(`\n${passed} checks passed.`);
const reportIndex=process.argv.indexOf("--report");if(reportIndex>=0)writeFileSync(process.argv[reportIndex+1],JSON.stringify(report,null,2));
