import {fresh,rooms,props,move,nearby,actions,interact,fight,usePotion,openBox,encode,decode,say} from './engine.mjs';
const $=id=>document.getElementById(id), canvas=$('game'),ctx=canvas.getContext('2d'), STORAGE='dungeoncrawlers.floor1.v1';
let state=fresh(),target=null,busy=false,lastKey=0;
function saved(){try{return decode(localStorage.getItem(STORAGE));}catch{return null;}}
function save(){const raw=encode(state);if(!raw)return false;try{localStorage.setItem(STORAGE,raw);$('savestatus').textContent='Saved in this browser. Progress does not sync between devices.';return true;}catch{$('savestatus').textContent='Saving is unavailable in this browser. Keep this tab open to continue.';return false;}}
function modal(title,text,buttons){$('modaltitle').textContent=title;$('modaltext').textContent=text;$('modalbuttons').replaceChildren();for(const [label,fn] of buttons){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{$('modal').close();fn();};$('modalbuttons').append(b);}if(!$('modal').open)$('modal').showModal();}
function load(){const s=saved();if(!s){modal('No living save found','Your save is missing, damaged, or from an unsupported version. Start a new game to begin.',[['Back',()=>{}],['New game',newGame]]);return;}state=s;target=null;render();}
function newGame(){state=fresh();target=null;save();render();}
function restart(){modal('Start a new shift?','This replaces your saved progress in this browser.',[['Keep playing',()=>{}],['Start new game',newGame]]);}
function endScreen(){if(state.dead)modal('Employment terminated.','Congratulations. You have successfully discovered what zero hit points means. Your last living save is safe.',[['Load save',load],['New game',restart]]);if(state.complete)modal('You clocked out alive.','Floor one complete. You found a key and reached the stairs.\nAchievements: '+(state.achievements.join(', ')||'None this time')+'\nThanks for surviving your probationary period.',[['Load save',load],['New game',restart]]);}
function changed(){if(!state.dead&&!state.complete&&!state.combat)save();render();endScreen();}
function step(dx,dy){if(busy||$('modal').open)return;if(move(state,dx,dy)){target=null;changed();}}
function select(){if(state.combat||state.dead||state.complete)return;const near=nearby(state);if(!near.length){say(state,'Move next to a character or object first.');render();return;}target=near[0].id;render();if(innerWidth<681)$('actioncard').scrollIntoView({behavior:'smooth',block:'nearest'});}
function action(label){if(busy||$('modal').open)return;busy=true;if(state.combat)fight(state,label);else interact(state,target,label);changed();setTimeout(()=>{busy=false;render();},350);}
function button(label,fn){const b=document.createElement('button');b.textContent=label;b.disabled=busy;b.onclick=fn;return b;}
function render(){
 $('rooms').replaceChildren(...rooms.map((r,i)=>{const el=document.createElement('span');el.className=i===state.room?'active':'';const n=document.createElement('b');n.textContent='0'+(i+1);el.append(n,document.createTextNode(r));return el;}));
 $('roomtitle').textContent=rooms[state.room];$('mode').textContent=state.dead?'DECEASED':state.complete?'CLOCKED OUT':state.combat?'YOUR TURN · COMBAT':'EXPLORING';$('hp').textContent=`${state.hp} / ${state.maxHp} HP`;$('healthbar').style.width=(100*state.hp/state.maxHp)+'%';$('healthbar').style.background=state.hp<10?'#db8272':'var(--accent)';$('gold').textContent=state.gold;$('key').textContent=state.key?'YES':'—';$('coordinates').textContent=`${state.x}, ${state.y}`;$('objective').textContent=state.key?'Exit key acquired. Keep heading east to Departures and use the stairs.':'Head east. Mara or her emergency locker has an exit key. Fighting is optional.';
 $('inventory').replaceChildren(...[`${state.potions} × Healing potion`,`${state.cheese} × Cheese`,`${state.boxes} × Loot box`,state.key?'1 × Exit key':'No exit key'].map(t=>{let el=document.createElement('span');el.textContent=t;return el;}));$('achievements').textContent=state.achievements.map(a=>'◇ '+a).join(' · ');$('packcount').textContent=`${state.potions+state.cheese+state.boxes} ITEMS`;
 const stopped=!!(state.combat||state.dead||state.complete);$('potion').disabled=stopped||!state.potions||state.hp===30;$('box').disabled=stopped||!state.boxes;$('save').disabled=stopped;$('interact').disabled=stopped;document.querySelectorAll('[data-move]').forEach(b=>b.disabled=stopped);$('load').disabled=!saved();
 $('log').replaceChildren(...state.log.slice(-10).map(t=>{let el=document.createElement('li');el.textContent=t;return el;}));$('log').scrollTop=$('log').scrollHeight;
 const near=nearby(state);if(!near.some(p=>p.id===target))target=null;if(!target&&near.length===1)target=near[0].id;
 $('actions').replaceChildren();if(state.combat){const id=state.combat.enemy;$('target').textContent=`${id==='rat'?'Ratman custodian':'Mara'} · ${state.npcs[id].hp} HP`;$('targethint').textContent=`Your turn. Enemy damage: ${id==='rat'?'2–3':'4–6'}. One response per action. Flee costs one hit.`;for(const a of ['Attack','Defend','Use potion','Flee'])$('actions').append(button(a,()=>action(a)));}
 else if(target){$('target').textContent=props[state.room].find(p=>p.id===target).name;$('targethint').textContent='Choose an action. Inspecting never starts combat.';for(const a of actions(state,target))$('actions').append(button(a,()=>action(a)));}
 else{$('target').textContent=near.length?'Choose something nearby':'Nothing within reach';$('targethint').textContent='Walk beside a character or prop, then interact.';for(const p of near)$('actions').append(button(p.name,()=>{target=p.id;render();}));}
 draw();
}
const palettes=[['#303c38','#34413a','#718269'],['#38372d','#403e31','#8a7850'],['#333a3b','#394243','#7d8880'],['#293e3d','#2c4642','#648a76'],['#3b3941','#44414b','#8c8294']];
function rect(x,y,w,h,color){ctx.fillStyle=color;ctx.fillRect(x,y,w,h);}
function sprite(x,y,type,dead=false){const px=x*64,py=y*64;rect(px+15,py+45,36,9,'#10191888');if(dead){rect(px+15,py+39,36,12,'#77695c');rect(px+42,py+33,10,10,'#ac9674');return;}
 if(type==='player'||type==='mara'||type==='rat'){let coat=type==='player'?'#c7dc94':type==='mara'?'#c3916b':'#94a387';rect(px+23,py+13,21,18,type==='rat'?'#a5aa89':'#d8b991');rect(px+20,py+29,27,21,coat);rect(px+21,py+48,9,9,'#192a2b');rect(px+37,py+48,9,9,'#192a2b');rect(px+16,py+31,6,16,coat);rect(px+47,py+31,6,16,coat);rect(px+32,py+19,4,4,'#172222');rect(px+41,py+19,4,4,'#172222');if(type==='player'){rect(px+22,py+8,23,9,'#3b5750');rect(px+16,py+13,35,5,'#3b5750');rect(px+26,py+33,5,17,'#7b905f');}if(type==='rat'){rect(px+18,py+7,11,11,coat);rect(px+39,py+7,11,11,coat);rect(px+43,py+24,10,7,'#babc94');}return;}
 if(type==='chest'||type==='crate'){rect(px+12,py+24,42,29,'#665036');rect(px+12,py+18,42,13,'#a6804e');rect(px+15,py+23,36,3,'#bc9963');rect(px+16,py+33,34,3,'#493b2c');rect(px+30,py+28,7,12,'#dfc782');if(type==='crate'){rect(px+17,py+20,5,33,'#bb9461');rect(px+45,py+20,5,33,'#bb9461');}return;}
 if(type==='fountain'){rect(px+9,py+27,47,25,'#697d76');rect(px+14,py+22,37,24,'#92a599');rect(px+19,py+27,27,13,'#6bc1b0');rect(px+23,py+30,10,3,'#a4e2c7');rect(px+27,py+10,10,16,'#8ba79d');return;}
 if(type==='stairs'){for(let i=0;i<5;i++){rect(px+5+i*5,py+51-i*9,53-i*7,8,i%2?'#abb6a1':'#849483');}return;}
 if(type==='pipe'){rect(px+9,py+22,45,12,'#70867d');rect(px+40,py+22,12,28,'#70867d');rect(px+15,py+19,5,18,'#a0aba0');rect(px+38,py+40,16,5,'#a0aba0');return;}
 if(type==='note'){rect(px+19,py+21,28,33,'#cabd8d');for(let i=0;i<4;i++)rect(px+24,py+28+i*5,16,2,'#786c4c');return;}
 rect(px+14,py+11,37,44,'#687b76');rect(px+18,py+15,29,29,type==='terminal'?'#283e35':'#424f4a');if(type==='terminal'){rect(px+22,py+20,20,3,'#c9e896');rect(px+22,py+27,13,3,'#c9e896');}else{rect(px+39,py+32,4,7,'#d1b97b');}rect(px+17,py+53,7,5,'#172725');rect(px+43,py+53,7,5,'#172725');
}
function draw(){const [a,b,wall]=palettes[state.room];ctx.clearRect(0,0,832,576);rect(0,0,832,576,'#111b1c');for(let y=0;y<9;y++)for(let x=0;x<13;x++){const edge=x===0||x===12||y===0||y===8;const door=y===4&&((x===0&&state.room>0)||(x===12&&state.room<4));rect(x*64+1,y*64+1,62,62,edge&&!door?'#28312f':(x+y)%2?a:b);if(edge&&!door){rect(x*64+2,y*64+4,60,11,wall);rect(x*64+3,y*64+20,58,3,'#151f1d');rect(x*64+31,y*64+4,3,16,'#222e2b');}else{rect(x*64+6,y*64+58,52,2,'#1b292644');if((x*7+y*11)%6===0)rect(x*64+13,y*64+21,8,3,'#6a766033');if(door){ctx.fillStyle='#d8e69c';ctx.font='24px monospace';ctx.fillText(x===0?'←':'→',x*64+21,y*64+39);}}}
 for(const p of props[state.room]){const near=nearby(state).some(n=>n.id===p.id);if(near){ctx.strokeStyle='#d9ec9b';ctx.lineWidth=2;ctx.strokeRect(p.x*64+5,p.y*64+4,54,55);}sprite(p.x,p.y,p.id,state.npcs[p.id]?.state==='dead');if((p.id==='chest'&&state.flags.chest)||(p.id==='crate'&&state.flags.crate)){rect(p.x*64+8,p.y*64+28,49,4,'#1b2420');}if(state.npcs[p.id]?.state==='friendly'){ctx.fillStyle='#d9ec9b';ctx.font='13px monospace';ctx.fillText('♥',p.x*64+28,p.y*64+5);}}
 ctx.strokeStyle='#cce59e55';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(state.x*64+33,state.y*64+53,24,8,0,0,Math.PI*2);ctx.stroke();sprite(state.x,state.y,'player',state.dead);
 ctx.fillStyle='#cbd8bb';ctx.font='12px monospace';ctx.textAlign='center';ctx.fillText('YOU',state.x*64+33,state.y*64+3);ctx.textAlign='left';
}
document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>step(...b.dataset.move.split(',').map(Number)));
document.addEventListener('keydown',e=>{if($('modal').open||['INPUT','TEXTAREA'].includes(e.target.tagName))return;const dirs={ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1],ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0]};const key=e.key.length===1?e.key.toLowerCase():e.key;if(dirs[key]){e.preventDefault();if(Date.now()-lastKey>105){step(...dirs[key]);lastKey=Date.now();}}if(key==='e'&&!e.repeat)select();});
canvas.addEventListener('click',e=>{if($('modal').open||state.combat)return;const r=canvas.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)/r.width*13),y=Math.floor((e.clientY-r.top)/r.height*9),p=nearby(state).find(p=>p.x===x&&p.y===y);if(p){target=p.id;render();if(innerWidth<681)$('actioncard').scrollIntoView({behavior:'smooth',block:'nearest'});}else if(Math.abs(x-state.x)+Math.abs(y-state.y)===1)step(x-state.x,y-state.y);});
$('interact').onclick=select;$('potion').onclick=()=>{if(usePotion(state))changed();};$('box').onclick=()=>{if(openBox(state))changed();};$('save').onclick=()=>{if(save()){say(state,'Progress saved.');render();}};$('load').onclick=()=>modal('Load your last save?','This restores your latest living checkpoint.',[['Cancel',()=>{}],['Load save',load]]);$('new').onclick=restart;
$('help').onclick=()=>modal('Employee orientation','Move with WASD, arrow keys, or the touch arrows. Doorways sit halfway along each side of a room.\nStand beside an object and choose an action. Walk around enemies to avoid combat.\nFind a key from Mara or her locker, then head east to the stairs. Potions heal 10 HP. The station in Intake fully heals you.\nDuring combat, every successful action allows one enemy response. Inspecting and opening menus do not.\nProgress saves automatically outside combat. Saves belong to this browser only.',[['Got it',()=>{}]]);
$('modal').addEventListener('cancel',e=>{if(state.dead||state.complete)e.preventDefault();});
render();const prior=saved();if(prior)modal('Back for another shift?','A living save was found in this browser. Continue your escape, or start a new game.',[['Continue',load],['New game',restart]]);else{save();render();}
