import {fresh,rooms,props,move,nearby,roomProps,actions,interact,fight,usePotion,useBandage,useWhetstone,openBox,encode,decode,say,attackRange,combatActions,outcome,conditionText,chooseStat,xpForNext,classReady,classOptions,chooseClass,CLASSES,RACES,achievementFor} from './engine.mjs?v=npc1';
import {PEOPLE,NPCS,tradePrice,itemName,memoryText,stockText,withPlayer} from './npcs.mjs';
import {bindHoldControls} from './controls.mjs';
const $=id=>document.getElementById(id),canvas=$('game'),screen=canvas.getContext('2d'),world=document.createElement('canvas');world.width=832;world.height=576;const ctx=world.getContext('2d'),STORAGE='dungeoncrawlers.floor1.v1';
let state=fresh(),target=null,busy=false,lastKey=0,actionOpen=false,toastTimer,bannerTimer,controls=null,feedback='',npcTab='social',camera={x:0,y:0,scale:1},visual={x:3,y:5},motion=null,frame=0;
const dialogs=['modal','pack-modal','menu-modal','journal-modal'];
function anyDialog(){return dialogs.some(id=>$(id).open);}
function stopHold(){controls?.stop();}
function openPanel(id){stopHold();dialogs.forEach(d=>{if($(d).open)$(d).close();});$(id).showModal();}
function saved(){try{return decode(localStorage.getItem(STORAGE));}catch{return null;}}
function save(){const raw=encode(state);if(!raw)return false;try{localStorage.setItem(STORAGE,raw);$('savestatus').textContent='Saved on this device. Saves do not sync between browsers.';return true;}catch{$('savestatus').textContent='Saving is unavailable. Keep this game open to preserve your progress.';return false;}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),5000);}
// The Dungeon AI popup. Several unlocks can land at once, so they queue and
// each gets its own moment in the banner.
let awardQueue=[],awardTimer=null;
function showAward(){if(!awardQueue.length){$('toast').classList.remove('show','achievement');return;}
 const name=awardQueue.shift(),entry=achievementFor(name);
 $('toast').textContent=`NEW ACHIEVEMENT ${awardQueue.length?`(${awardQueue.length} more)`:''}: ${name}\n“${entry?entry.message:'Logged. The dungeon saw that.'}”`;
 $('toast').classList.add('show','achievement');clearTimeout(awardTimer);
 awardTimer=setTimeout(showAward,4500);}
function announce(from){const won=state.achievements.slice(from);if(!won.length)return;
 awardQueue.push(...won);clearTimeout(awardTimer);showAward();}
function modal(title,text,buttons){$('modaltitle').textContent=title;$('modaltext').textContent=text;$('modalbuttons').replaceChildren();for(const [label,fn] of buttons){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{$('modal').close();fn();};$('modalbuttons').append(b);}openPanel('modal');}
function resetView(){awardQueue.length=0;clearTimeout(awardTimer);target=null;npcTab='social';actionOpen=false;feedback='';motion=null;visual={x:state.x,y:state.y};dialogs.forEach(d=>$(d).close());stopHold();}
function load(){const s=saved();if(!s){modal('No living save found','Your save is missing or damaged.',[['Back',()=>{}],['New game',newGame]]);return;}state=s;resetView();render();if(state.complete)endScreen();else toast("Welcome back, crawler.");promptEvents();}
function newGame(){state=fresh();resetView();save();render();toast('Find a key, then head east to the stairs.');}
function restart(){modal('Start a new shift?','This replaces your saved progress on this device.',[['Keep playing',()=>{if(state.dead||state.complete)endScreen();}],['Start new game',newGame]]);}
function endScreen(){if(state.dead)modal('Employment terminated.','Congratulations. You have discovered what zero hit points means. Your last living save is safe.',[['Load save',load],['New game',restart]]);if(state.complete)modal('You clocked out alive.','ANNEX: “You escaped. Your reputation went ahead.”\n\n'+outcome(state)+'\n\nAchievements: '+(state.achievements.join(', ')||'None this time'),[['Load save',load],['New game',restart]]);}
function changed(){if(!state.dead&&!state.combat)save();render();endScreen();promptEvents();}
// The level-up screen: +5 maximum HP is already applied, then one ability point.
function pickStat(ability){chooseStat(state,ability);save();render();toast(ability+' increased.');promptLevel();}
function promptLevel(){if(state.combat||state.dead||state.complete||!(state.pending>0)||anyDialog())return;
 modal(`Level ${state.level}`,`Maximum HP is now ${state.maxHp}. Choose one ability to increase.`,[['Strength',()=>pickStat('strength')],['Dexterity',()=>pickStat('dexterity')],['Constitution',()=>pickStat('constitution')],['Intelligence',()=>pickStat('intelligence')],['Wisdom',()=>pickStat('wisdom')],['Charisma',()=>pickStat('charisma')]]);}
// The class event fires once the crawler's habits are clear enough to read.
function takeClass(id){chooseClass(state,id);save();render();toast(CLASSES[id].name+' chosen.');promptEvents();}
function promptClass(){if(state.combat||state.dead||state.complete||!classReady(state)||anyDialog())return;
 const options=classOptions(state);
 modal('Choose a path',`You have survived long enough to specialise. Your habits point at ${options.map(id=>CLASSES[id].name).join(', ')}.`,options.map(id=>[CLASSES[id].name,()=>takeClass(id)]));}
function promptEvents(){promptLevel();promptClass();}
function step(dx,dy){if(busy||anyDialog()||actionOpen)return;const oldRoom=state.room,oldSerial=state.logSerial;const from={...visual};if(move(state,dx,dy)){target=null;feedback='';if(state.room!==oldRoom){motion=null;visual={x:state.x,y:state.y};$('room-banner').textContent=rooms[state.room].toUpperCase();$('room-banner').classList.add('show');clearTimeout(bannerTimer);bannerTimer=setTimeout(()=>$('room-banner').classList.remove('show'),1600);const news=state.log.slice(-(state.logSerial-oldSerial)).filter(line=>!line.startsWith('Entered '));if(news.length)toast(news.join(' '));}else if(matchMedia('(prefers-reduced-motion: reduce)').matches){motion=null;visual={x:state.x,y:state.y};}else motion={from,to:{x:state.x,y:state.y},start:performance.now()};changed();}}
function select(){if(state.combat||state.dead||state.complete||anyDialog())return;stopHold();const near=nearby(state);if(!near.length){toast('Move beside an object or character.');return;}target=near.length===1?near[0].id:null;actionOpen=true;npcTab='social';feedback='';render();}
function action(label,confirmed=false){if(busy||anyDialog())return;if(label==='Kill'&&!confirmed){modal('Kill '+NPCS[target].name+'?',state.npcs[target].condition==='unconscious'?'They are unconscious and cannot fight back. This kills them permanently in this playthrough.':NPCS[target].name+' will fight back. This starts lethal combat.',[['Cancel',()=>{}],['Kill',()=>action(label,true)]]);return;}stopHold();busy=true;const wasCombat=!!state.combat,oldSerial=state.logSerial,oldPosition={x:state.x,y:state.y},oldAwards=state.achievements.length;if(state.combat)fight(state,label);else interact(state,target,label);feedback=state.log.slice(-(state.logSerial-oldSerial||0)).filter((_,i)=>state.logSerial!==oldSerial).join(' ');if(state.x!==oldPosition.x||state.y!==oldPosition.y){motion=null;visual={x:state.x,y:state.y};}if(wasCombat&&!state.combat){actionOpen=false;toast(feedback);}else actionOpen=true;changed();announce(oldAwards);setTimeout(()=>{busy=false;render();},350);}
function button(label,fn){const b=document.createElement('button');b.textContent=label;b.disabled=busy;b.onclick=fn;return b;}
function render(){
 $('rooms').replaceChildren(...rooms.map((r,i)=>{const el=document.createElement('span');el.className=i===state.room?'active':'';el.setAttribute('aria-label',r);if(i===state.room)el.setAttribute('aria-current','step');return el;}));
 $('roomtitle').textContent=rooms[state.room];$('mode').textContent=(state.combat?'YOUR TURN':'EXPLORING')+(conditionText(state,'player')?' · '+conditionText(state,'player'):'');$('hp').textContent=`${state.hp} / ${state.maxHp}`;$('healthbar').style.width=(100*state.hp/state.maxHp)+'%';$('healthbar').style.background=state.hp<10?'#e08e73':'var(--lime)';$('gold').textContent=state.gold;$('objective').textContent=(state.class!=='crawler'?CLASSES[state.class].name+' · ':'')+`Lv ${state.level} · ${state.xp}/${xpForNext(state.level)} XP`+(state.pending>0?' · LEVEL UP':(state.key?' · Key acquired · Head east':' · Find an exit key'));
 $('inventory').replaceChildren(...[`${state.potions} × Healing potion`,`${state.cheese} × Cheese`,`${state.boxes} × Loot box`,state.key?'1 × Exit key':'No exit key yet',...Object.entries(state.items).map(([key,n])=>`${n} × ${itemName[key]}`),`Attack: ${attackRange(state).join('–')}`].map(t=>{const el=document.createElement('span');el.textContent=t;return el;}));
 // One line per achievement so a long list stays readable and scrollable.
 $('achievements').replaceChildren(...(state.achievements.length?state.achievements.map(name=>{const entry=achievementFor(name),row=document.createElement('article'),title=document.createElement('strong'),line=document.createElement('p');
  title.textContent='◇ '+name;line.textContent=(entry?entry.description:'Logged by the dungeon.')+(entry?` (${entry.reward})`:'');row.append(title,line);return row;}):[Object.assign(document.createElement('p'),{textContent:'Nothing yet. Try doing something regrettable.'})]));
 $('packcount').textContent=state.potions+state.cheese+state.boxes+Object.values(state.items).reduce((a,b)=>a+b,0);
 const stopped=!!(state.combat||state.dead||state.complete);$('potion').disabled=stopped||!state.potions||state.hp===30;$('box').disabled=stopped||!state.boxes;$('bandage').disabled=stopped||!state.items.bandages||state.hp===30;$('sharpen').disabled=stopped||!state.items.whetstones;$('save').disabled=stopped;$('load').disabled=!saved();document.querySelectorAll('[data-move]').forEach(b=>b.disabled=stopped);
 $('relationships').replaceChildren(...PEOPLE.map(id=>{const n=state.npcs[id],card=document.createElement('article');const h=document.createElement('strong');h.textContent=NPCS[id].name+' · '+n.attitude+' · '+n.condition;const p=document.createElement('p');p.textContent=memoryText(n)+'. Remaining possessions: '+stockText(n)+'.';card.append(h,p);return card;}));
 $('log').replaceChildren(...state.log.map(t=>{const el=document.createElement('li');el.textContent=t;return el;}));
 const near=nearby(state);if(!near.some(p=>p.id===target))target=null;if(!target&&near.length===1)target=near[0].id;
 $('interact').disabled=stopped||!near.length;$('nearby-label').textContent=near.length?'✦ '+near.map(p=>p.name).join(' / '):'Explore the room';$('shell').classList.toggle('combat',!!state.combat);document.querySelector('.west').hidden=state.room===0;document.querySelector('.east').hidden=state.room===4;
 if(state.combat)actionOpen=true;const showing=actionOpen&&!state.dead&&!state.complete;$('actioncard').hidden=!showing;document.querySelector('.explore-controls').hidden=showing;$('close-actions').hidden=!!state.combat;$('action-label').textContent=state.combat?'COMBAT · YOUR TURN':'WITHIN REACH';$('action-feedback').textContent=feedback;
 const person=target&&PEOPLE.includes(target)&&state.npcs[target].condition==='conscious'&&!state.combat;$('npc-tabs').hidden=!person;document.querySelectorAll('[data-npc-tab]').forEach(b=>{const on=b.dataset.npcTab===npcTab;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));});
 $('actions').replaceChildren();if(state.combat){const id=state.combat.enemy,d=NPCS[id],nonlethal=state.combat.intent==='nonlethal';$('target').textContent=d.name+' · '+state.npcs[id].hp+' HP'+(state.combat.enemies.length>1?' · '+state.combat.enemies.length+' ENEMIES':'')+' · RANGE '+state.combat.range;$('targethint').textContent=(nonlethal?'NONLETHAL':'LETHAL')+' · Your damage '+attackRange(state).map(n=>n-(nonlethal?1:0)).join('–')+' · Enemy '+d.damage.join('–')+(conditionText(state,id)?' · '+conditionText(state,id).toUpperCase():'');for(const a of combatActions(state)){const b=button(a,()=>action(a));if(a==='Use potion')b.disabled=busy||!state.potions||state.hp===30;if(a==='Smoke bomb')b.disabled=busy||!state.items.smokeBombs;$('actions').append(b);}}
 else if(target){const n=state.npcs[target];$('target').textContent=(roomProps(state).find(p=>p.id===target)||{}).name||target;let hint=n?n.attitude.toUpperCase()+' · '+n.condition+' · '+n.hp+'/'+NPCS[target].hp+' HP'+((state.party||[]).includes(target)?' · IN YOUR PARTY':(state.allies?.[target]>0?` · ALLY (${state.allies[target]})`:'')):'Choose what happens next.';if(person)hint+=npcTab==='social'?' · Help: '+NPCS[target].help:npcTab==='supplies'?' · Trade: 1 '+itemName[NPCS[target].trade]+' / '+tradePrice(state,target)+' coins':' · Attack/Kill are lethal. Knock unconscious starts nonlethal combat.';$('targethint').textContent=hint;let available=actions(state,target);if(person){const groups={social:['Inspect','Talk','Help','Befriend','Recruit','Lie','Hand it back'],supplies:['Trade','Ask about goods','Offer a fair swap','Pickpocket','Rob openly','Inspect'],conflict:['Threaten','Attack','Knock unconscious','Kill']};available=available.filter(a=>groups[npcTab].includes(a)||(npcTab==='supplies'&&a.startsWith('Sell 1 ')));}for(const a of available)$('actions').append(button(a,()=>action(a)));}
 else{$('target').textContent='Choose an object';$('targethint').textContent='These are within reach.';for(const p of near)$('actions').append(button(p.name,()=>{target=p.id;npcTab='social';feedback='';render();}));}

 scheduleDraw();
}
function scheduleDraw(){if(!frame)frame=requestAnimationFrame(t=>{frame=0;if(motion){const p=Math.min(1,(t-motion.start)/140),e=1-(1-p)*(1-p);visual.x=motion.from.x+(motion.to.x-motion.from.x)*e;visual.y=motion.from.y+(motion.to.y-motion.from.y)*e;if(p===1)motion=null;}draw();if(motion)scheduleDraw();});}
function present(){const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return;const dpr=Math.min(devicePixelRatio||1,2),w=Math.round(r.width*dpr),h=Math.round(r.height*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}const scale=Math.max(r.width/832,r.height/576,.82);const x=Math.max(0,Math.min(832-r.width/scale,visual.x*64+32-r.width/scale/2)),y=Math.max(0,Math.min(576-r.height/scale,visual.y*64+32-r.height/scale/2));camera={x,y,scale};screen.setTransform(dpr,0,0,dpr,0,0);screen.imageSmoothingEnabled=false;screen.clearRect(0,0,r.width,r.height);screen.drawImage(world,x,y,r.width/scale,r.height/scale,0,0,r.width,r.height);}
const palettes=[['#303c38','#34413a','#718269'],['#38372d','#403e31','#8a7850'],['#333a3b','#394243','#7d8880'],['#293e3d','#2c4642','#648a76'],['#3b3941','#44414b','#8c8294']];
function rect(x,y,w,h,color){ctx.fillStyle=color;ctx.fillRect(x,y,w,h);}
function sprite(x,y,type,condition='conscious'){const px=x*64,py=y*64;rect(px+15,py+45,36,9,'#10191888');if(condition==='dead'||condition==='unconscious'){rect(px+15,py+39,36,12,'#77695c');rect(px+42,py+33,10,10,'#ac9674');ctx.font='13px monospace';ctx.fillStyle=condition==='dead'?'#df8f80':'#b5d6e9';ctx.fillText(condition==='dead'?'×':'Zz',px+25,py+24);return;}
 if(['player','mara','tobin','vex','rat'].includes(type)){let coat=({player:'#c7dc94',mara:'#c3916b',tobin:'#dfb366',vex:'#ae9fcf',rat:'#94a387'})[type];rect(px+23,py+13,21,18,type==='rat'?'#a5aa89':'#d8b991');rect(px+20,py+29,27,21,coat);rect(px+21,py+48,9,9,'#192a2b');rect(px+37,py+48,9,9,'#192a2b');rect(px+16,py+31,6,16,coat);rect(px+47,py+31,6,16,coat);rect(px+32,py+19,4,4,'#172222');rect(px+41,py+19,4,4,'#172222');if(type==='player'){rect(px+22,py+8,23,9,'#3b5750');rect(px+16,py+13,35,5,'#3b5750');rect(px+26,py+33,5,17,'#7b905f');}if(type==='tobin'){rect(px+15,py+33,12,19,'#775232');rect(px+19,py+10,27,8,'#ae8442');}if(type==='vex'){rect(px+22,py+30,24,10,'#626886');rect(px+51,py+15,4,30,'#d7dfdf');rect(px+47,py+41,13,4,'#cbae76');}if(type==='rat'){rect(px+18,py+7,11,11,coat);rect(px+39,py+7,11,11,coat);rect(px+43,py+24,10,7,'#babc94');}return;}
 if(type==='chest'||type==='crate'){rect(px+12,py+24,42,29,'#665036');rect(px+12,py+18,42,13,'#a6804e');rect(px+15,py+23,36,3,'#bc9963');rect(px+16,py+33,34,3,'#493b2c');rect(px+30,py+28,7,12,'#dfc782');if(type==='crate'){rect(px+17,py+20,5,33,'#bb9461');rect(px+45,py+20,5,33,'#bb9461');}return;}
 if(type==='fountain'){rect(px+9,py+27,47,25,'#697d76');rect(px+14,py+22,37,24,'#92a599');rect(px+19,py+27,27,13,'#6bc1b0');rect(px+23,py+30,10,3,'#a4e2c7');rect(px+27,py+10,10,16,'#8ba79d');return;}
 if(type==='stairs'){for(let i=0;i<5;i++){rect(px+5+i*5,py+51-i*9,53-i*7,8,i%2?'#abb6a1':'#849483');}return;}
 if(type==='pipe'){rect(px+9,py+22,45,12,'#70867d');rect(px+40,py+22,12,28,'#70867d');rect(px+15,py+19,5,18,'#a0aba0');rect(px+38,py+40,16,5,'#a0aba0');return;}
 if(type==='note'){rect(px+19,py+21,28,33,'#cabd8d');for(let i=0;i<4;i++)rect(px+24,py+28+i*5,16,2,'#786c4c');return;}
 rect(px+14,py+11,37,44,'#687b76');rect(px+18,py+15,29,29,type==='terminal'?'#283e35':'#424f4a');if(type==='terminal'){rect(px+22,py+20,20,3,'#c9e896');rect(px+22,py+27,13,3,'#c9e896');}else{rect(px+39,py+32,4,7,'#d1b97b');}rect(px+17,py+53,7,5,'#172725');rect(px+43,py+53,7,5,'#172725');
}
function draw(){const [a,b,wall]=palettes[state.room];ctx.clearRect(0,0,832,576);rect(0,0,832,576,'#111b1c');for(let y=0;y<9;y++)for(let x=0;x<13;x++){const edge=x===0||x===12||y===0||y===8;const door=y===4&&((x===0&&state.room>0)||(x===12&&state.room<4));rect(x*64+1,y*64+1,62,62,edge&&!door?'#28312f':(x+y)%2?a:b);if(edge&&!door){rect(x*64+2,y*64+4,60,11,wall);rect(x*64+3,y*64+20,58,3,'#151f1d');rect(x*64+31,y*64+4,3,16,'#222e2b');}else{rect(x*64+6,y*64+58,52,2,'#1b292644');if((x*7+y*11)%6===0)rect(x*64+13,y*64+21,8,3,'#6a766033');if(door){ctx.fillStyle='#d8e69c';ctx.font='24px monospace';ctx.fillText(x===0?'←':'→',x*64+21,y*64+39);}}}
 for(const p of roomProps(state)){const near=nearby(state).some(n=>n.id===p.id);if(near){ctx.strokeStyle='#d9ec9b';ctx.lineWidth=2;ctx.strokeRect(p.x*64+5,p.y*64+4,54,55);}sprite(p.x,p.y,p.id,state.npcs[p.id]?.condition||'conscious');if((p.id==='chest'&&state.flags.chest)||(p.id==='crate'&&state.flags.crate)){rect(p.x*64+8,p.y*64+28,49,4,'#1b2420');}if(state.npcs[p.id]?.attitude==='friendly'&&state.npcs[p.id]?.condition==='conscious'){ctx.fillStyle='#d9ec9b';ctx.font='13px monospace';ctx.fillText('♥',p.x*64+28,p.y*64+5);}}
 for(const p of roomProps(state).filter(p=>PEOPLE.includes(p.id))){ctx.font='11px monospace';ctx.textAlign='center';ctx.fillStyle=({friendly:'#d6ef9b',neutral:'#e5dcc3',suspicious:'#e4ba75',hostile:'#e8988d'})[state.npcs[p.id].attitude];ctx.fillText(withPlayer(state).includes(p.id)?NPCS[p.id].name+' ✦':NPCS[p.id].name,p.x*64+32,p.y*64+3);ctx.textAlign='left';}
 ctx.strokeStyle='#cce59e55';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(visual.x*64+33,visual.y*64+53,24,8,0,0,Math.PI*2);ctx.stroke();sprite(visual.x,visual.y,'player',state.dead?'dead':'conscious');
 ctx.fillStyle='#cbd8bb';ctx.font='12px monospace';ctx.textAlign='center';ctx.fillText('YOU',visual.x*64+33,visual.y*64+3);ctx.textAlign='left';present();
}
controls=bindHoldControls(document.querySelectorAll('[data-move]'),{move:step,canMove:()=>!busy&&!anyDialog()&&!actionOpen&&!state.combat&&!state.dead&&!state.complete});
window.addEventListener('blur',stopHold);document.addEventListener('visibilitychange',()=>{stopHold();if(document.hidden)save();});
document.addEventListener('keydown',e=>{if(anyDialog())return;const dirs={ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1],ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0]};const key=e.key.length===1?e.key.toLowerCase():e.key;if(dirs[key]){e.preventDefault();if(Date.now()-lastKey>105){step(...dirs[key]);lastKey=Date.now();}}if(key==='e'&&!e.repeat)select();if(key==='Escape'&&!state.combat){actionOpen=false;render();}});
canvas.addEventListener('click',e=>{if(anyDialog()||state.combat||actionOpen)return;const r=canvas.getBoundingClientRect(),x=Math.floor((camera.x+(e.clientX-r.left)/camera.scale)/64),y=Math.floor((camera.y+(e.clientY-r.top)/camera.scale)/64),p=nearby(state).find(p=>p.x===x&&p.y===y);if(p){target=p.id;npcTab='social';actionOpen=true;feedback='';render();}else if(Math.abs(x-state.x)+Math.abs(y-state.y)===1)step(x-state.x,y-state.y);});
document.querySelectorAll('[data-npc-tab]').forEach(b=>b.onclick=()=>{npcTab=b.dataset.npcTab;render();});
$('bandage').onclick=()=>{if(useBandage(state)){changed();$('pack-feedback').textContent=state.log.at(-1);}};$('sharpen').onclick=()=>{if(useWhetstone(state)){changed();$('pack-feedback').textContent=state.log.at(-1);}};
$('interact').onclick=select;$('close-actions').onclick=()=>{actionOpen=false;feedback='';render();};$('menu').onclick=()=>openPanel('menu-modal');$('pack').onclick=()=>{$('pack-feedback').textContent='';openPanel('pack-modal');};$('journal').onclick=()=>openPanel('journal-modal');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('potion').onclick=()=>{if(usePotion(state)){changed();$('pack-feedback').textContent=state.log.at(-1);}};$('box').onclick=()=>{if(openBox(state)){changed();$('pack-feedback').textContent=state.log.at(-1);}};$('save').onclick=()=>{if(save())$('savestatus').textContent='Saved. You can return to this browser to continue.';};$('load').onclick=()=>modal('Load your last save?','Return to your latest living checkpoint.',[['Cancel',()=>{}],['Load save',load]]);$('new').onclick=restart;
$('help').onclick=()=>modal('Your first shift','Hold a direction to move. The camera follows you. Doorways are halfway along the east and west walls.\nStand beside a character or object, then tap Interact.\nFind an exit key from Mara or her locker, then reach the stairs. Fighting is optional.\nNPC approaches are grouped into Social, Supplies, and Conflict. Their attitudes, injuries, possessions, and memories persist. Pickpocketed NPCs notice on room exit. Field notes show relationship history.\nIn combat, use nonlethal mode to knock out or lethal mode to kill. Switching intent is free. Smoke escapes without a hit. Potions heal 10 HP; defend halves the next hit.\nProgress saves on this device outside combat. Open the menu to save, load, or restart.',[['Let’s go',()=>{}]]);
$('modal').addEventListener('cancel',e=>{if(state.dead||state.complete)e.preventDefault();});new ResizeObserver(scheduleDraw).observe($('viewport'));
render();const prior=saved();if(prior)modal('Back for another shift?','Your last living checkpoint is ready.',[['Continue',load],['New game',restart]]);else{save();render();toast('Find a key. Reach the stairs. Try not to die.');}
// Offline play: the service worker precaches the game shell so a Home Screen
// launch works without a connection. Registration is silent and harmless
// where the API or a secure context is missing.
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});
